/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table;


import com.example.mvc.table.tables.TAccount;
import com.example.mvc.table.tables.TAccountBindingUser;
import com.example.mvc.table.tables.TAccountOperateRecord;
import com.example.mvc.table.tables.TActivityText;
import com.example.mvc.table.tables.TBigvVerifyRecord;
import com.example.mvc.table.tables.TDayLabelSumRecord;
import com.example.mvc.table.tables.TDepartment;
import com.example.mvc.table.tables.TFeedLabelRecord;
import com.example.mvc.table.tables.TFlag;
import com.example.mvc.table.tables.TNetdiskRecord;
import com.example.mvc.table.tables.TOperate;
import com.example.mvc.table.tables.TOperateCategory;
import com.example.mvc.table.tables.TPrizeFake;
import com.example.mvc.table.tables.TPrizeUser;
import com.example.mvc.table.tables.TPrizeUserAll;
import com.example.mvc.table.tables.TProject;
import com.example.mvc.table.tables.TRecheckRecord;
import com.example.mvc.table.tables.TRecommendTopic;
import com.example.mvc.table.tables.TResource;
import com.example.mvc.table.tables.TRole;
import com.example.mvc.table.tables.TRoleAccount;
import com.example.mvc.table.tables.TRoleOperate;
import com.example.mvc.table.tables.TRoleProject;
import com.example.mvc.table.tables.TRoomMemberCheck;
import com.example.mvc.table.tables.TShareRecord;
import com.example.mvc.table.tables.TTopicAttribute;
import com.example.mvc.table.tables.TUserMessage;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Kelu extends SchemaImpl {

    private static final long serialVersionUID = -610725225;

    /**
     * The reference instance of <code>kelu</code>
     */
    public static final Kelu kelu = new Kelu();

    /**
     * 用户表
     */
    public final TAccount t_account = TAccount.t_account;

    /**
     * The table <code>kelu.t_account_binding_user</code>.
     */
    public final TAccountBindingUser t_account_binding_user = TAccountBindingUser.t_account_binding_user;

    /**
     * The table <code>kelu.t_account_operate_record</code>.
     */
    public final TAccountOperateRecord t_account_operate_record = TAccountOperateRecord.t_account_operate_record;

    /**
     * 文案表
     */
    public final TActivityText t_activity_text = TActivityText.t_activity_text;

    /**
     * The table <code>kelu.t_bigv_verify_record</code>.
     */
    public final TBigvVerifyRecord t_bigv_verify_record = TBigvVerifyRecord.t_bigv_verify_record;

    /**
     * The table <code>kelu.t_day_label_sum_record</code>.
     */
    public final TDayLabelSumRecord t_day_label_sum_record = TDayLabelSumRecord.t_day_label_sum_record;

    /**
     * The table <code>kelu.t_department</code>.
     */
    public final TDepartment t_department = TDepartment.t_department;

    /**
     * The table <code>kelu.t_feed_label_record</code>.
     */
    public final TFeedLabelRecord t_feed_label_record = TFeedLabelRecord.t_feed_label_record;

    /**
     * The table <code>kelu.t_flag</code>.
     */
    public final TFlag t_flag = TFlag.t_flag;

    /**
     * The table <code>kelu.t_netdisk_record</code>.
     */
    public final TNetdiskRecord t_netdisk_record = TNetdiskRecord.t_netdisk_record;

    /**
     * The table <code>kelu.t_operate</code>.
     */
    public final TOperate t_operate = TOperate.t_operate;

    /**
     * The table <code>kelu.t_operate_category</code>.
     */
    public final TOperateCategory t_operate_category = TOperateCategory.t_operate_category;

    /**
     * 有奖征集视频假名单
     */
    public final TPrizeFake t_prize_fake = TPrizeFake.t_prize_fake;

    /**
     * 中奖用户
     */
    public final TPrizeUser t_prize_user = TPrizeUser.t_prize_user;

    /**
     * 所有中奖用户名单
     */
    public final TPrizeUserAll t_prize_user_all = TPrizeUserAll.t_prize_user_all;

    /**
     * The table <code>kelu.t_project</code>.
     */
    public final TProject t_project = TProject.t_project;

    /**
     * 房间复查记录表
     */
    public final TRecheckRecord t_recheck_record = TRecheckRecord.t_recheck_record;

    /**
     * The table <code>kelu.t_recommend_topic</code>.
     */
    public final TRecommendTopic t_recommend_topic = TRecommendTopic.t_recommend_topic;

    /**
     * The table <code>kelu.t_resource</code>.
     */
    public final TResource t_resource = TResource.t_resource;

    /**
     * The table <code>kelu.t_role</code>.
     */
    public final TRole t_role = TRole.t_role;

    /**
     * The table <code>kelu.t_role_account</code>.
     */
    public final TRoleAccount t_role_account = TRoleAccount.t_role_account;

    /**
     * The table <code>kelu.t_role_operate</code>.
     */
    public final TRoleOperate t_role_operate = TRoleOperate.t_role_operate;

    /**
     * The table <code>kelu.t_role_project</code>.
     */
    public final TRoleProject t_role_project = TRoleProject.t_role_project;

    /**
     * The table <code>kelu.t_room_member_check</code>.
     */
    public final TRoomMemberCheck t_room_member_check = TRoomMemberCheck.t_room_member_check;

    /**
     * The table <code>kelu.t_share_record</code>.
     */
    public final TShareRecord t_share_record = TShareRecord.t_share_record;

    /**
     * The table <code>kelu.t_topic_attribute</code>.
     */
    public final TTopicAttribute t_topic_attribute = TTopicAttribute.t_topic_attribute;

    /**
     * The table <code>kelu.t_user_message</code>.
     */
    public final TUserMessage t_user_message = TUserMessage.t_user_message;

    /**
     * No further instances allowed
     */
    private Kelu() {
        super("kelu", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TAccount.t_account,
            TAccountBindingUser.t_account_binding_user,
            TAccountOperateRecord.t_account_operate_record,
            TActivityText.t_activity_text,
            TBigvVerifyRecord.t_bigv_verify_record,
            TDayLabelSumRecord.t_day_label_sum_record,
            TDepartment.t_department,
            TFeedLabelRecord.t_feed_label_record,
            TFlag.t_flag,
            TNetdiskRecord.t_netdisk_record,
            TOperate.t_operate,
            TOperateCategory.t_operate_category,
            TPrizeFake.t_prize_fake,
            TPrizeUser.t_prize_user,
            TPrizeUserAll.t_prize_user_all,
            TProject.t_project,
            TRecheckRecord.t_recheck_record,
            TRecommendTopic.t_recommend_topic,
            TResource.t_resource,
            TRole.t_role,
            TRoleAccount.t_role_account,
            TRoleOperate.t_role_operate,
            TRoleProject.t_role_project,
            TRoomMemberCheck.t_room_member_check,
            TShareRecord.t_share_record,
            TTopicAttribute.t_topic_attribute,
            TUserMessage.t_user_message);
    }
}
