/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table;


import com.example.mvc.table.tables.TAccount;
import com.example.mvc.table.tables.TAccountBindingUser;
import com.example.mvc.table.tables.TAccountOperateRecord;
import com.example.mvc.table.tables.TActivityText;
import com.example.mvc.table.tables.TBigvVerifyRecord;
import com.example.mvc.table.tables.TDayLabelSumRecord;
import com.example.mvc.table.tables.TDepartment;
import com.example.mvc.table.tables.TFeedLabelRecord;
import com.example.mvc.table.tables.TFlag;
import com.example.mvc.table.tables.TNetdiskRecord;
import com.example.mvc.table.tables.TOperate;
import com.example.mvc.table.tables.TOperateCategory;
import com.example.mvc.table.tables.TPrizeFake;
import com.example.mvc.table.tables.TPrizeUser;
import com.example.mvc.table.tables.TPrizeUserAll;
import com.example.mvc.table.tables.TProject;
import com.example.mvc.table.tables.TRecheckRecord;
import com.example.mvc.table.tables.TRecommendTopic;
import com.example.mvc.table.tables.TResource;
import com.example.mvc.table.tables.TRole;
import com.example.mvc.table.tables.TRoleAccount;
import com.example.mvc.table.tables.TRoleOperate;
import com.example.mvc.table.tables.TRoleProject;
import com.example.mvc.table.tables.TRoomMemberCheck;
import com.example.mvc.table.tables.TShareRecord;
import com.example.mvc.table.tables.TTopicAttribute;
import com.example.mvc.table.tables.TUserMessage;
import com.example.mvc.table.tables.records.TAccountBindingUserRecord;
import com.example.mvc.table.tables.records.TAccountOperateRecordRecord;
import com.example.mvc.table.tables.records.TAccountRecord;
import com.example.mvc.table.tables.records.TActivityTextRecord;
import com.example.mvc.table.tables.records.TBigvVerifyRecordRecord;
import com.example.mvc.table.tables.records.TDayLabelSumRecordRecord;
import com.example.mvc.table.tables.records.TDepartmentRecord;
import com.example.mvc.table.tables.records.TFeedLabelRecordRecord;
import com.example.mvc.table.tables.records.TFlagRecord;
import com.example.mvc.table.tables.records.TNetdiskRecordRecord;
import com.example.mvc.table.tables.records.TOperateCategoryRecord;
import com.example.mvc.table.tables.records.TOperateRecord;
import com.example.mvc.table.tables.records.TPrizeFakeRecord;
import com.example.mvc.table.tables.records.TPrizeUserAllRecord;
import com.example.mvc.table.tables.records.TPrizeUserRecord;
import com.example.mvc.table.tables.records.TProjectRecord;
import com.example.mvc.table.tables.records.TRecheckRecordRecord;
import com.example.mvc.table.tables.records.TRecommendTopicRecord;
import com.example.mvc.table.tables.records.TResourceRecord;
import com.example.mvc.table.tables.records.TRoleAccountRecord;
import com.example.mvc.table.tables.records.TRoleOperateRecord;
import com.example.mvc.table.tables.records.TRoleProjectRecord;
import com.example.mvc.table.tables.records.TRoleRecord;
import com.example.mvc.table.tables.records.TRoomMemberCheckRecord;
import com.example.mvc.table.tables.records.TShareRecordRecord;
import com.example.mvc.table.tables.records.TTopicAttributeRecord;
import com.example.mvc.table.tables.records.TUserMessageRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>kelu</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TAccountRecord, Integer> IDENTITY_t_account = Identities0.IDENTITY_t_account;
    public static final Identity<TAccountBindingUserRecord, Integer> IDENTITY_t_account_binding_user = Identities0.IDENTITY_t_account_binding_user;
    public static final Identity<TAccountOperateRecordRecord, Integer> IDENTITY_t_account_operate_record = Identities0.IDENTITY_t_account_operate_record;
    public static final Identity<TActivityTextRecord, Integer> IDENTITY_t_activity_text = Identities0.IDENTITY_t_activity_text;
    public static final Identity<TBigvVerifyRecordRecord, Integer> IDENTITY_t_bigv_verify_record = Identities0.IDENTITY_t_bigv_verify_record;
    public static final Identity<TDayLabelSumRecordRecord, Integer> IDENTITY_t_day_label_sum_record = Identities0.IDENTITY_t_day_label_sum_record;
    public static final Identity<TDepartmentRecord, Integer> IDENTITY_t_department = Identities0.IDENTITY_t_department;
    public static final Identity<TFeedLabelRecordRecord, Integer> IDENTITY_t_feed_label_record = Identities0.IDENTITY_t_feed_label_record;
    public static final Identity<TFlagRecord, Integer> IDENTITY_t_flag = Identities0.IDENTITY_t_flag;
    public static final Identity<TNetdiskRecordRecord, Integer> IDENTITY_t_netdisk_record = Identities0.IDENTITY_t_netdisk_record;
    public static final Identity<TOperateRecord, Integer> IDENTITY_t_operate = Identities0.IDENTITY_t_operate;
    public static final Identity<TOperateCategoryRecord, Integer> IDENTITY_t_operate_category = Identities0.IDENTITY_t_operate_category;
    public static final Identity<TPrizeFakeRecord, Integer> IDENTITY_t_prize_fake = Identities0.IDENTITY_t_prize_fake;
    public static final Identity<TPrizeUserRecord, Integer> IDENTITY_t_prize_user = Identities0.IDENTITY_t_prize_user;
    public static final Identity<TPrizeUserAllRecord, Integer> IDENTITY_t_prize_user_all = Identities0.IDENTITY_t_prize_user_all;
    public static final Identity<TProjectRecord, Integer> IDENTITY_t_project = Identities0.IDENTITY_t_project;
    public static final Identity<TRecheckRecordRecord, Integer> IDENTITY_t_recheck_record = Identities0.IDENTITY_t_recheck_record;
    public static final Identity<TRecommendTopicRecord, Integer> IDENTITY_t_recommend_topic = Identities0.IDENTITY_t_recommend_topic;
    public static final Identity<TResourceRecord, Integer> IDENTITY_t_resource = Identities0.IDENTITY_t_resource;
    public static final Identity<TRoleRecord, Integer> IDENTITY_t_role = Identities0.IDENTITY_t_role;
    public static final Identity<TRoleAccountRecord, Integer> IDENTITY_t_role_account = Identities0.IDENTITY_t_role_account;
    public static final Identity<TRoleOperateRecord, Integer> IDENTITY_t_role_operate = Identities0.IDENTITY_t_role_operate;
    public static final Identity<TRoleProjectRecord, Integer> IDENTITY_t_role_project = Identities0.IDENTITY_t_role_project;
    public static final Identity<TRoomMemberCheckRecord, Integer> IDENTITY_t_room_member_check = Identities0.IDENTITY_t_room_member_check;
    public static final Identity<TShareRecordRecord, Integer> IDENTITY_t_share_record = Identities0.IDENTITY_t_share_record;
    public static final Identity<TTopicAttributeRecord, Integer> IDENTITY_t_topic_attribute = Identities0.IDENTITY_t_topic_attribute;
    public static final Identity<TUserMessageRecord, Integer> IDENTITY_t_user_message = Identities0.IDENTITY_t_user_message;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TAccountRecord> KEY_t_account_PRIMARY = UniqueKeys0.KEY_t_account_PRIMARY;
    public static final UniqueKey<TAccountBindingUserRecord> KEY_t_account_binding_user_PRIMARY = UniqueKeys0.KEY_t_account_binding_user_PRIMARY;
    public static final UniqueKey<TAccountOperateRecordRecord> KEY_t_account_operate_record_PRIMARY = UniqueKeys0.KEY_t_account_operate_record_PRIMARY;
    public static final UniqueKey<TActivityTextRecord> KEY_t_activity_text_PRIMARY = UniqueKeys0.KEY_t_activity_text_PRIMARY;
    public static final UniqueKey<TBigvVerifyRecordRecord> KEY_t_bigv_verify_record_PRIMARY = UniqueKeys0.KEY_t_bigv_verify_record_PRIMARY;
    public static final UniqueKey<TDayLabelSumRecordRecord> KEY_t_day_label_sum_record_PRIMARY = UniqueKeys0.KEY_t_day_label_sum_record_PRIMARY;
    public static final UniqueKey<TDepartmentRecord> KEY_t_department_PRIMARY = UniqueKeys0.KEY_t_department_PRIMARY;
    public static final UniqueKey<TFeedLabelRecordRecord> KEY_t_feed_label_record_PRIMARY = UniqueKeys0.KEY_t_feed_label_record_PRIMARY;
    public static final UniqueKey<TFlagRecord> KEY_t_flag_PRIMARY = UniqueKeys0.KEY_t_flag_PRIMARY;
    public static final UniqueKey<TNetdiskRecordRecord> KEY_t_netdisk_record_PRIMARY = UniqueKeys0.KEY_t_netdisk_record_PRIMARY;
    public static final UniqueKey<TOperateRecord> KEY_t_operate_PRIMARY = UniqueKeys0.KEY_t_operate_PRIMARY;
    public static final UniqueKey<TOperateCategoryRecord> KEY_t_operate_category_PRIMARY = UniqueKeys0.KEY_t_operate_category_PRIMARY;
    public static final UniqueKey<TPrizeFakeRecord> KEY_t_prize_fake_PRIMARY = UniqueKeys0.KEY_t_prize_fake_PRIMARY;
    public static final UniqueKey<TPrizeUserRecord> KEY_t_prize_user_PRIMARY = UniqueKeys0.KEY_t_prize_user_PRIMARY;
    public static final UniqueKey<TPrizeUserAllRecord> KEY_t_prize_user_all_PRIMARY = UniqueKeys0.KEY_t_prize_user_all_PRIMARY;
    public static final UniqueKey<TProjectRecord> KEY_t_project_PRIMARY = UniqueKeys0.KEY_t_project_PRIMARY;
    public static final UniqueKey<TRecheckRecordRecord> KEY_t_recheck_record_PRIMARY = UniqueKeys0.KEY_t_recheck_record_PRIMARY;
    public static final UniqueKey<TRecommendTopicRecord> KEY_t_recommend_topic_PRIMARY = UniqueKeys0.KEY_t_recommend_topic_PRIMARY;
    public static final UniqueKey<TResourceRecord> KEY_t_resource_PRIMARY = UniqueKeys0.KEY_t_resource_PRIMARY;
    public static final UniqueKey<TRoleRecord> KEY_t_role_PRIMARY = UniqueKeys0.KEY_t_role_PRIMARY;
    public static final UniqueKey<TRoleAccountRecord> KEY_t_role_account_PRIMARY = UniqueKeys0.KEY_t_role_account_PRIMARY;
    public static final UniqueKey<TRoleOperateRecord> KEY_t_role_operate_PRIMARY = UniqueKeys0.KEY_t_role_operate_PRIMARY;
    public static final UniqueKey<TRoleProjectRecord> KEY_t_role_project_PRIMARY = UniqueKeys0.KEY_t_role_project_PRIMARY;
    public static final UniqueKey<TRoomMemberCheckRecord> KEY_t_room_member_check_PRIMARY = UniqueKeys0.KEY_t_room_member_check_PRIMARY;
    public static final UniqueKey<TShareRecordRecord> KEY_t_share_record_PRIMARY = UniqueKeys0.KEY_t_share_record_PRIMARY;
    public static final UniqueKey<TTopicAttributeRecord> KEY_t_topic_attribute_PRIMARY = UniqueKeys0.KEY_t_topic_attribute_PRIMARY;
    public static final UniqueKey<TUserMessageRecord> KEY_t_user_message_PRIMARY = UniqueKeys0.KEY_t_user_message_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<TAccountRecord, Integer> IDENTITY_t_account = Internal.createIdentity(TAccount.t_account, TAccount.t_account.id);
        public static Identity<TAccountBindingUserRecord, Integer> IDENTITY_t_account_binding_user = Internal.createIdentity(TAccountBindingUser.t_account_binding_user, TAccountBindingUser.t_account_binding_user.id);
        public static Identity<TAccountOperateRecordRecord, Integer> IDENTITY_t_account_operate_record = Internal.createIdentity(TAccountOperateRecord.t_account_operate_record, TAccountOperateRecord.t_account_operate_record.id);
        public static Identity<TActivityTextRecord, Integer> IDENTITY_t_activity_text = Internal.createIdentity(TActivityText.t_activity_text, TActivityText.t_activity_text.id);
        public static Identity<TBigvVerifyRecordRecord, Integer> IDENTITY_t_bigv_verify_record = Internal.createIdentity(TBigvVerifyRecord.t_bigv_verify_record, TBigvVerifyRecord.t_bigv_verify_record.id);
        public static Identity<TDayLabelSumRecordRecord, Integer> IDENTITY_t_day_label_sum_record = Internal.createIdentity(TDayLabelSumRecord.t_day_label_sum_record, TDayLabelSumRecord.t_day_label_sum_record.id);
        public static Identity<TDepartmentRecord, Integer> IDENTITY_t_department = Internal.createIdentity(TDepartment.t_department, TDepartment.t_department.id);
        public static Identity<TFeedLabelRecordRecord, Integer> IDENTITY_t_feed_label_record = Internal.createIdentity(TFeedLabelRecord.t_feed_label_record, TFeedLabelRecord.t_feed_label_record.id);
        public static Identity<TFlagRecord, Integer> IDENTITY_t_flag = Internal.createIdentity(TFlag.t_flag, TFlag.t_flag.id);
        public static Identity<TNetdiskRecordRecord, Integer> IDENTITY_t_netdisk_record = Internal.createIdentity(TNetdiskRecord.t_netdisk_record, TNetdiskRecord.t_netdisk_record.id);
        public static Identity<TOperateRecord, Integer> IDENTITY_t_operate = Internal.createIdentity(TOperate.t_operate, TOperate.t_operate.id);
        public static Identity<TOperateCategoryRecord, Integer> IDENTITY_t_operate_category = Internal.createIdentity(TOperateCategory.t_operate_category, TOperateCategory.t_operate_category.id);
        public static Identity<TPrizeFakeRecord, Integer> IDENTITY_t_prize_fake = Internal.createIdentity(TPrizeFake.t_prize_fake, TPrizeFake.t_prize_fake.id);
        public static Identity<TPrizeUserRecord, Integer> IDENTITY_t_prize_user = Internal.createIdentity(TPrizeUser.t_prize_user, TPrizeUser.t_prize_user.id);
        public static Identity<TPrizeUserAllRecord, Integer> IDENTITY_t_prize_user_all = Internal.createIdentity(TPrizeUserAll.t_prize_user_all, TPrizeUserAll.t_prize_user_all.id);
        public static Identity<TProjectRecord, Integer> IDENTITY_t_project = Internal.createIdentity(TProject.t_project, TProject.t_project.id);
        public static Identity<TRecheckRecordRecord, Integer> IDENTITY_t_recheck_record = Internal.createIdentity(TRecheckRecord.t_recheck_record, TRecheckRecord.t_recheck_record.id);
        public static Identity<TRecommendTopicRecord, Integer> IDENTITY_t_recommend_topic = Internal.createIdentity(TRecommendTopic.t_recommend_topic, TRecommendTopic.t_recommend_topic.id);
        public static Identity<TResourceRecord, Integer> IDENTITY_t_resource = Internal.createIdentity(TResource.t_resource, TResource.t_resource.id);
        public static Identity<TRoleRecord, Integer> IDENTITY_t_role = Internal.createIdentity(TRole.t_role, TRole.t_role.id);
        public static Identity<TRoleAccountRecord, Integer> IDENTITY_t_role_account = Internal.createIdentity(TRoleAccount.t_role_account, TRoleAccount.t_role_account.id);
        public static Identity<TRoleOperateRecord, Integer> IDENTITY_t_role_operate = Internal.createIdentity(TRoleOperate.t_role_operate, TRoleOperate.t_role_operate.id);
        public static Identity<TRoleProjectRecord, Integer> IDENTITY_t_role_project = Internal.createIdentity(TRoleProject.t_role_project, TRoleProject.t_role_project.id);
        public static Identity<TRoomMemberCheckRecord, Integer> IDENTITY_t_room_member_check = Internal.createIdentity(TRoomMemberCheck.t_room_member_check, TRoomMemberCheck.t_room_member_check.id);
        public static Identity<TShareRecordRecord, Integer> IDENTITY_t_share_record = Internal.createIdentity(TShareRecord.t_share_record, TShareRecord.t_share_record.id);
        public static Identity<TTopicAttributeRecord, Integer> IDENTITY_t_topic_attribute = Internal.createIdentity(TTopicAttribute.t_topic_attribute, TTopicAttribute.t_topic_attribute.id);
        public static Identity<TUserMessageRecord, Integer> IDENTITY_t_user_message = Internal.createIdentity(TUserMessage.t_user_message, TUserMessage.t_user_message.id);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<TAccountRecord> KEY_t_account_PRIMARY = Internal.createUniqueKey(TAccount.t_account, "KEY_t_account_PRIMARY", TAccount.t_account.id);
        public static final UniqueKey<TAccountBindingUserRecord> KEY_t_account_binding_user_PRIMARY = Internal.createUniqueKey(TAccountBindingUser.t_account_binding_user, "KEY_t_account_binding_user_PRIMARY", TAccountBindingUser.t_account_binding_user.id);
        public static final UniqueKey<TAccountOperateRecordRecord> KEY_t_account_operate_record_PRIMARY = Internal.createUniqueKey(TAccountOperateRecord.t_account_operate_record, "KEY_t_account_operate_record_PRIMARY", TAccountOperateRecord.t_account_operate_record.id);
        public static final UniqueKey<TActivityTextRecord> KEY_t_activity_text_PRIMARY = Internal.createUniqueKey(TActivityText.t_activity_text, "KEY_t_activity_text_PRIMARY", TActivityText.t_activity_text.id);
        public static final UniqueKey<TBigvVerifyRecordRecord> KEY_t_bigv_verify_record_PRIMARY = Internal.createUniqueKey(TBigvVerifyRecord.t_bigv_verify_record, "KEY_t_bigv_verify_record_PRIMARY", TBigvVerifyRecord.t_bigv_verify_record.id);
        public static final UniqueKey<TDayLabelSumRecordRecord> KEY_t_day_label_sum_record_PRIMARY = Internal.createUniqueKey(TDayLabelSumRecord.t_day_label_sum_record, "KEY_t_day_label_sum_record_PRIMARY", TDayLabelSumRecord.t_day_label_sum_record.id);
        public static final UniqueKey<TDepartmentRecord> KEY_t_department_PRIMARY = Internal.createUniqueKey(TDepartment.t_department, "KEY_t_department_PRIMARY", TDepartment.t_department.id);
        public static final UniqueKey<TFeedLabelRecordRecord> KEY_t_feed_label_record_PRIMARY = Internal.createUniqueKey(TFeedLabelRecord.t_feed_label_record, "KEY_t_feed_label_record_PRIMARY", TFeedLabelRecord.t_feed_label_record.id);
        public static final UniqueKey<TFlagRecord> KEY_t_flag_PRIMARY = Internal.createUniqueKey(TFlag.t_flag, "KEY_t_flag_PRIMARY", TFlag.t_flag.id);
        public static final UniqueKey<TNetdiskRecordRecord> KEY_t_netdisk_record_PRIMARY = Internal.createUniqueKey(TNetdiskRecord.t_netdisk_record, "KEY_t_netdisk_record_PRIMARY", TNetdiskRecord.t_netdisk_record.id);
        public static final UniqueKey<TOperateRecord> KEY_t_operate_PRIMARY = Internal.createUniqueKey(TOperate.t_operate, "KEY_t_operate_PRIMARY", TOperate.t_operate.id);
        public static final UniqueKey<TOperateCategoryRecord> KEY_t_operate_category_PRIMARY = Internal.createUniqueKey(TOperateCategory.t_operate_category, "KEY_t_operate_category_PRIMARY", TOperateCategory.t_operate_category.id);
        public static final UniqueKey<TPrizeFakeRecord> KEY_t_prize_fake_PRIMARY = Internal.createUniqueKey(TPrizeFake.t_prize_fake, "KEY_t_prize_fake_PRIMARY", TPrizeFake.t_prize_fake.id);
        public static final UniqueKey<TPrizeUserRecord> KEY_t_prize_user_PRIMARY = Internal.createUniqueKey(TPrizeUser.t_prize_user, "KEY_t_prize_user_PRIMARY", TPrizeUser.t_prize_user.id);
        public static final UniqueKey<TPrizeUserAllRecord> KEY_t_prize_user_all_PRIMARY = Internal.createUniqueKey(TPrizeUserAll.t_prize_user_all, "KEY_t_prize_user_all_PRIMARY", TPrizeUserAll.t_prize_user_all.id);
        public static final UniqueKey<TProjectRecord> KEY_t_project_PRIMARY = Internal.createUniqueKey(TProject.t_project, "KEY_t_project_PRIMARY", TProject.t_project.id);
        public static final UniqueKey<TRecheckRecordRecord> KEY_t_recheck_record_PRIMARY = Internal.createUniqueKey(TRecheckRecord.t_recheck_record, "KEY_t_recheck_record_PRIMARY", TRecheckRecord.t_recheck_record.id);
        public static final UniqueKey<TRecommendTopicRecord> KEY_t_recommend_topic_PRIMARY = Internal.createUniqueKey(TRecommendTopic.t_recommend_topic, "KEY_t_recommend_topic_PRIMARY", TRecommendTopic.t_recommend_topic.id);
        public static final UniqueKey<TResourceRecord> KEY_t_resource_PRIMARY = Internal.createUniqueKey(TResource.t_resource, "KEY_t_resource_PRIMARY", TResource.t_resource.id);
        public static final UniqueKey<TRoleRecord> KEY_t_role_PRIMARY = Internal.createUniqueKey(TRole.t_role, "KEY_t_role_PRIMARY", TRole.t_role.id);
        public static final UniqueKey<TRoleAccountRecord> KEY_t_role_account_PRIMARY = Internal.createUniqueKey(TRoleAccount.t_role_account, "KEY_t_role_account_PRIMARY", TRoleAccount.t_role_account.id);
        public static final UniqueKey<TRoleOperateRecord> KEY_t_role_operate_PRIMARY = Internal.createUniqueKey(TRoleOperate.t_role_operate, "KEY_t_role_operate_PRIMARY", TRoleOperate.t_role_operate.id);
        public static final UniqueKey<TRoleProjectRecord> KEY_t_role_project_PRIMARY = Internal.createUniqueKey(TRoleProject.t_role_project, "KEY_t_role_project_PRIMARY", TRoleProject.t_role_project.id);
        public static final UniqueKey<TRoomMemberCheckRecord> KEY_t_room_member_check_PRIMARY = Internal.createUniqueKey(TRoomMemberCheck.t_room_member_check, "KEY_t_room_member_check_PRIMARY", TRoomMemberCheck.t_room_member_check.id);
        public static final UniqueKey<TShareRecordRecord> KEY_t_share_record_PRIMARY = Internal.createUniqueKey(TShareRecord.t_share_record, "KEY_t_share_record_PRIMARY", TShareRecord.t_share_record.id);
        public static final UniqueKey<TTopicAttributeRecord> KEY_t_topic_attribute_PRIMARY = Internal.createUniqueKey(TTopicAttribute.t_topic_attribute, "KEY_t_topic_attribute_PRIMARY", TTopicAttribute.t_topic_attribute.id);
        public static final UniqueKey<TUserMessageRecord> KEY_t_user_message_PRIMARY = Internal.createUniqueKey(TUserMessage.t_user_message, "KEY_t_user_message_PRIMARY", TUserMessage.t_user_message.id);
    }
}
