/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables;


import com.example.mvc.table.Kelu;
import com.example.mvc.table.Keys;
import com.example.mvc.table.tables.records.TActivityTextRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 文案表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TActivityText extends TableImpl<TActivityTextRecord> {

    private static final long serialVersionUID = 6047113;

    /**
     * The reference instance of <code>kelu.t_activity_text</code>
     */
    public static final TActivityText t_activity_text = new TActivityText();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TActivityTextRecord> getRecordType() {
        return TActivityTextRecord.class;
    }

    /**
     * The column <code>kelu.t_activity_text.id</code>.
     */
    public final TableField<TActivityTextRecord, Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>kelu.t_activity_text.title</code>. 标题
     */
    public final TableField<TActivityTextRecord, String> title = createField("title", org.jooq.impl.SQLDataType.VARCHAR(100), this, "标题");

    /**
     * The column <code>kelu.t_activity_text.content</code>. 内容
     */
    public final TableField<TActivityTextRecord, String> content = createField("content", org.jooq.impl.SQLDataType.VARCHAR(200), this, "内容");

    /**
     * The column <code>kelu.t_activity_text.feedId</code>. 日志id
     */
    public final TableField<TActivityTextRecord, Integer> feedId = createField("feedId", org.jooq.impl.SQLDataType.INTEGER, this, "日志id");

    /**
     * The column <code>kelu.t_activity_text.video_file</code>. 视频文件名
     */
    public final TableField<TActivityTextRecord, String> video_file = createField("video_file", org.jooq.impl.SQLDataType.VARCHAR(300), this, "视频文件名");

    /**
     * The column <code>kelu.t_activity_text.cover_file</code>. 视频封面文件名
     */
    public final TableField<TActivityTextRecord, String> cover_file = createField("cover_file", org.jooq.impl.SQLDataType.VARCHAR(300), this, "视频封面文件名");

    /**
     * The column <code>kelu.t_activity_text.is_use</code>. 是否正在使用
     */
    public final TableField<TActivityTextRecord, Byte> is_use = createField("is_use", org.jooq.impl.SQLDataType.TINYINT, this, "是否正在使用");

    /**
     * The column <code>kelu.t_activity_text.post_time</code>.
     */
    public final TableField<TActivityTextRecord, LocalDateTime> post_time = createField("post_time", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>kelu.t_activity_text</code> table reference
     */
    public TActivityText() {
        this(DSL.name("t_activity_text"), null);
    }

    /**
     * Create an aliased <code>kelu.t_activity_text</code> table reference
     */
    public TActivityText(String alias) {
        this(DSL.name(alias), t_activity_text);
    }

    /**
     * Create an aliased <code>kelu.t_activity_text</code> table reference
     */
    public TActivityText(Name alias) {
        this(alias, t_activity_text);
    }

    private TActivityText(Name alias, Table<TActivityTextRecord> aliased) {
        this(alias, aliased, null);
    }

    private TActivityText(Name alias, Table<TActivityTextRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "文案表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kelu.kelu;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TActivityTextRecord, Integer> getIdentity() {
        return Keys.IDENTITY_t_activity_text;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TActivityTextRecord> getPrimaryKey() {
        return Keys.KEY_t_activity_text_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TActivityTextRecord>> getKeys() {
        return Arrays.<UniqueKey<TActivityTextRecord>>asList(Keys.KEY_t_activity_text_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityText as(String alias) {
        return new TActivityText(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityText as(Name alias) {
        return new TActivityText(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TActivityText rename(String name) {
        return new TActivityText(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TActivityText rename(Name name) {
        return new TActivityText(name, null);
    }
}
