/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables;


import com.example.mvc.table.Kelu;
import com.example.mvc.table.Keys;
import com.example.mvc.table.tables.records.TBigvVerifyRecordRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBigvVerifyRecord extends TableImpl<TBigvVerifyRecordRecord> {

    private static final long serialVersionUID = -581943;

    /**
     * The reference instance of <code>kelu.t_bigv_verify_record</code>
     */
    public static final TBigvVerifyRecord t_bigv_verify_record = new TBigvVerifyRecord();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TBigvVerifyRecordRecord> getRecordType() {
        return TBigvVerifyRecordRecord.class;
    }

    /**
     * The column <code>kelu.t_bigv_verify_record.id</code>.
     */
    public final TableField<TBigvVerifyRecordRecord, Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>kelu.t_bigv_verify_record.user_id</code>.
     */
    public final TableField<TBigvVerifyRecordRecord, Integer> user_id = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kelu.t_bigv_verify_record.account_id</code>.
     */
    public final TableField<TBigvVerifyRecordRecord, Integer> account_id = createField("account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kelu.t_bigv_verify_record.status</code>. 0 认证成功 1 认证失败
     */
    public final TableField<TBigvVerifyRecordRecord, Byte> status = createField("status", org.jooq.impl.SQLDataType.TINYINT, this, "0 认证成功 1 认证失败");

    /**
     * The column <code>kelu.t_bigv_verify_record.post_time</code>.
     */
    public final TableField<TBigvVerifyRecordRecord, LocalDateTime> post_time = createField("post_time", org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>kelu.t_bigv_verify_record</code> table reference
     */
    public TBigvVerifyRecord() {
        this(DSL.name("t_bigv_verify_record"), null);
    }

    /**
     * Create an aliased <code>kelu.t_bigv_verify_record</code> table reference
     */
    public TBigvVerifyRecord(String alias) {
        this(DSL.name(alias), t_bigv_verify_record);
    }

    /**
     * Create an aliased <code>kelu.t_bigv_verify_record</code> table reference
     */
    public TBigvVerifyRecord(Name alias) {
        this(alias, t_bigv_verify_record);
    }

    private TBigvVerifyRecord(Name alias, Table<TBigvVerifyRecordRecord> aliased) {
        this(alias, aliased, null);
    }

    private TBigvVerifyRecord(Name alias, Table<TBigvVerifyRecordRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kelu.kelu;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TBigvVerifyRecordRecord, Integer> getIdentity() {
        return Keys.IDENTITY_t_bigv_verify_record;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TBigvVerifyRecordRecord> getPrimaryKey() {
        return Keys.KEY_t_bigv_verify_record_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TBigvVerifyRecordRecord>> getKeys() {
        return Arrays.<UniqueKey<TBigvVerifyRecordRecord>>asList(Keys.KEY_t_bigv_verify_record_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBigvVerifyRecord as(String alias) {
        return new TBigvVerifyRecord(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBigvVerifyRecord as(Name alias) {
        return new TBigvVerifyRecord(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TBigvVerifyRecord rename(String name) {
        return new TBigvVerifyRecord(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TBigvVerifyRecord rename(Name name) {
        return new TBigvVerifyRecord(name, null);
    }
}
