/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables;


import com.example.mvc.table.Kelu;
import com.example.mvc.table.Keys;
import com.example.mvc.table.tables.records.TDayLabelSumRecordRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDayLabelSumRecord extends TableImpl<TDayLabelSumRecordRecord> {

    private static final long serialVersionUID = 75252273;

    /**
     * The reference instance of <code>kelu.t_day_label_sum_record</code>
     */
    public static final TDayLabelSumRecord t_day_label_sum_record = new TDayLabelSumRecord();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TDayLabelSumRecordRecord> getRecordType() {
        return TDayLabelSumRecordRecord.class;
    }

    /**
     * The column <code>kelu.t_day_label_sum_record.id</code>.
     */
    public final TableField<TDayLabelSumRecordRecord, Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>kelu.t_day_label_sum_record.account_id</code>. 客服ID
     */
    public final TableField<TDayLabelSumRecordRecord, Integer> account_id = createField("account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "客服ID");

    /**
     * The column <code>kelu.t_day_label_sum_record.start_time</code>.
     */
    public final TableField<TDayLabelSumRecordRecord, LocalDateTime> start_time = createField("start_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>kelu.t_day_label_sum_record.end_time</code>.
     */
    public final TableField<TDayLabelSumRecordRecord, LocalDateTime> end_time = createField("end_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>kelu.t_day_label_sum_record.date</code>.
     */
    public final TableField<TDayLabelSumRecordRecord, Long> date = createField("date", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>kelu.t_day_label_sum_record.label_count</code>.
     */
    public final TableField<TDayLabelSumRecordRecord, Integer> label_count = createField("label_count", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>kelu.t_day_label_sum_record</code> table reference
     */
    public TDayLabelSumRecord() {
        this(DSL.name("t_day_label_sum_record"), null);
    }

    /**
     * Create an aliased <code>kelu.t_day_label_sum_record</code> table reference
     */
    public TDayLabelSumRecord(String alias) {
        this(DSL.name(alias), t_day_label_sum_record);
    }

    /**
     * Create an aliased <code>kelu.t_day_label_sum_record</code> table reference
     */
    public TDayLabelSumRecord(Name alias) {
        this(alias, t_day_label_sum_record);
    }

    private TDayLabelSumRecord(Name alias, Table<TDayLabelSumRecordRecord> aliased) {
        this(alias, aliased, null);
    }

    private TDayLabelSumRecord(Name alias, Table<TDayLabelSumRecordRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kelu.kelu;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TDayLabelSumRecordRecord, Integer> getIdentity() {
        return Keys.IDENTITY_t_day_label_sum_record;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TDayLabelSumRecordRecord> getPrimaryKey() {
        return Keys.KEY_t_day_label_sum_record_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TDayLabelSumRecordRecord>> getKeys() {
        return Arrays.<UniqueKey<TDayLabelSumRecordRecord>>asList(Keys.KEY_t_day_label_sum_record_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDayLabelSumRecord as(String alias) {
        return new TDayLabelSumRecord(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDayLabelSumRecord as(Name alias) {
        return new TDayLabelSumRecord(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TDayLabelSumRecord rename(String name) {
        return new TDayLabelSumRecord(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TDayLabelSumRecord rename(Name name) {
        return new TDayLabelSumRecord(name, null);
    }
}
