/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables;


import com.example.mvc.table.Kelu;
import com.example.mvc.table.Keys;
import com.example.mvc.table.tables.records.TOperateRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOperate extends TableImpl<TOperateRecord> {

    private static final long serialVersionUID = -1678440342;

    /**
     * The reference instance of <code>kelu.t_operate</code>
     */
    public static final TOperate t_operate = new TOperate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TOperateRecord> getRecordType() {
        return TOperateRecord.class;
    }

    /**
     * The column <code>kelu.t_operate.id</code>.
     */
    public final TableField<TOperateRecord, Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>kelu.t_operate.operate_name</code>.
     */
    public final TableField<TOperateRecord, String> operate_name = createField("operate_name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>kelu.t_operate.category_id</code>.
     */
    public final TableField<TOperateRecord, Integer> category_id = createField("category_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kelu.t_operate.is_delete</code>.
     */
    public final TableField<TOperateRecord, Byte> is_delete = createField("is_delete", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * Create a <code>kelu.t_operate</code> table reference
     */
    public TOperate() {
        this(DSL.name("t_operate"), null);
    }

    /**
     * Create an aliased <code>kelu.t_operate</code> table reference
     */
    public TOperate(String alias) {
        this(DSL.name(alias), t_operate);
    }

    /**
     * Create an aliased <code>kelu.t_operate</code> table reference
     */
    public TOperate(Name alias) {
        this(alias, t_operate);
    }

    private TOperate(Name alias, Table<TOperateRecord> aliased) {
        this(alias, aliased, null);
    }

    private TOperate(Name alias, Table<TOperateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kelu.kelu;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TOperateRecord, Integer> getIdentity() {
        return Keys.IDENTITY_t_operate;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TOperateRecord> getPrimaryKey() {
        return Keys.KEY_t_operate_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TOperateRecord>> getKeys() {
        return Arrays.<UniqueKey<TOperateRecord>>asList(Keys.KEY_t_operate_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOperate as(String alias) {
        return new TOperate(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOperate as(Name alias) {
        return new TOperate(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TOperate rename(String name) {
        return new TOperate(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TOperate rename(Name name) {
        return new TOperate(name, null);
    }
}
