/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables;


import com.example.mvc.table.Kelu;
import com.example.mvc.table.Keys;
import com.example.mvc.table.tables.records.TPrizeUserRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 中奖用户
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPrizeUser extends TableImpl<TPrizeUserRecord> {

    private static final long serialVersionUID = 234782964;

    /**
     * The reference instance of <code>kelu.t_prize_user</code>
     */
    public static final TPrizeUser t_prize_user = new TPrizeUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TPrizeUserRecord> getRecordType() {
        return TPrizeUserRecord.class;
    }

    /**
     * The column <code>kelu.t_prize_user.id</code>.
     */
    public final TableField<TPrizeUserRecord, Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>kelu.t_prize_user.userId</code>. 用户Id
     */
    public final TableField<TPrizeUserRecord, Integer> userId = createField("userId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "用户Id");

    /**
     * The column <code>kelu.t_prize_user.nickname</code>. 昵称
     */
    public final TableField<TPrizeUserRecord, String> nickname = createField("nickname", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "昵称");

    /**
     * The column <code>kelu.t_prize_user.avatar_file</code>. 头像
     */
    public final TableField<TPrizeUserRecord, String> avatar_file = createField("avatar_file", org.jooq.impl.SQLDataType.VARCHAR(300).nullable(false), this, "头像");

    /**
     * The column <code>kelu.t_prize_user.type</code>. 1.每天中奖 2.5天中奖
     */
    public final TableField<TPrizeUserRecord, Byte> type = createField("type", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "1.每天中奖 2.5天中奖");

    /**
     * The column <code>kelu.t_prize_user.share_times</code>. 分享次数
     */
    public final TableField<TPrizeUserRecord, Integer> share_times = createField("share_times", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "分享次数");

    /**
     * The column <code>kelu.t_prize_user.prize_date</code>. 中奖日期
     */
    public final TableField<TPrizeUserRecord, LocalDate> prize_date = createField("prize_date", org.jooq.impl.SQLDataType.LOCALDATE.nullable(false), this, "中奖日期");

    /**
     * The column <code>kelu.t_prize_user.post_time</code>.
     */
    public final TableField<TPrizeUserRecord, LocalDateTime> post_time = createField("post_time", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>kelu.t_prize_user</code> table reference
     */
    public TPrizeUser() {
        this(DSL.name("t_prize_user"), null);
    }

    /**
     * Create an aliased <code>kelu.t_prize_user</code> table reference
     */
    public TPrizeUser(String alias) {
        this(DSL.name(alias), t_prize_user);
    }

    /**
     * Create an aliased <code>kelu.t_prize_user</code> table reference
     */
    public TPrizeUser(Name alias) {
        this(alias, t_prize_user);
    }

    private TPrizeUser(Name alias, Table<TPrizeUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private TPrizeUser(Name alias, Table<TPrizeUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "中奖用户");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kelu.kelu;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TPrizeUserRecord, Integer> getIdentity() {
        return Keys.IDENTITY_t_prize_user;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TPrizeUserRecord> getPrimaryKey() {
        return Keys.KEY_t_prize_user_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TPrizeUserRecord>> getKeys() {
        return Arrays.<UniqueKey<TPrizeUserRecord>>asList(Keys.KEY_t_prize_user_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeUser as(String alias) {
        return new TPrizeUser(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeUser as(Name alias) {
        return new TPrizeUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TPrizeUser rename(String name) {
        return new TPrizeUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TPrizeUser rename(Name name) {
        return new TPrizeUser(name, null);
    }
}
