/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables;


import com.example.mvc.table.Kelu;
import com.example.mvc.table.Keys;
import com.example.mvc.table.tables.records.TPrizeFakeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 有奖征集视频假名单
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPrizeFake extends TableImpl<TPrizeFakeRecord> {

    private static final long serialVersionUID = -503431836;

    /**
     * The reference instance of <code>kelu.t_prize_fake</code>
     */
    public static final TPrizeFake t_prize_fake = new TPrizeFake();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TPrizeFakeRecord> getRecordType() {
        return TPrizeFakeRecord.class;
    }

    /**
     * The column <code>kelu.t_prize_fake.id</code>.
     */
    public final TableField<TPrizeFakeRecord, Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>kelu.t_prize_fake.userId</code>. 用户id
     */
    public final TableField<TPrizeFakeRecord, Integer> userId = createField("userId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "用户id");

    /**
     * The column <code>kelu.t_prize_fake.nikename</code>. 昵称
     */
    public final TableField<TPrizeFakeRecord, String> nikename = createField("nikename", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "昵称");

    /**
     * The column <code>kelu.t_prize_fake.avatar_file</code>. 头像文件名
     */
    public final TableField<TPrizeFakeRecord, String> avatar_file = createField("avatar_file", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "头像文件名");

    /**
     * Create a <code>kelu.t_prize_fake</code> table reference
     */
    public TPrizeFake() {
        this(DSL.name("t_prize_fake"), null);
    }

    /**
     * Create an aliased <code>kelu.t_prize_fake</code> table reference
     */
    public TPrizeFake(String alias) {
        this(DSL.name(alias), t_prize_fake);
    }

    /**
     * Create an aliased <code>kelu.t_prize_fake</code> table reference
     */
    public TPrizeFake(Name alias) {
        this(alias, t_prize_fake);
    }

    private TPrizeFake(Name alias, Table<TPrizeFakeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TPrizeFake(Name alias, Table<TPrizeFakeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "有奖征集视频假名单");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kelu.kelu;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TPrizeFakeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_t_prize_fake;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TPrizeFakeRecord> getPrimaryKey() {
        return Keys.KEY_t_prize_fake_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TPrizeFakeRecord>> getKeys() {
        return Arrays.<UniqueKey<TPrizeFakeRecord>>asList(Keys.KEY_t_prize_fake_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeFake as(String alias) {
        return new TPrizeFake(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeFake as(Name alias) {
        return new TPrizeFake(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TPrizeFake rename(String name) {
        return new TPrizeFake(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TPrizeFake rename(Name name) {
        return new TPrizeFake(name, null);
    }
}
