/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables;


import com.example.mvc.table.Kelu;
import com.example.mvc.table.Keys;
import com.example.mvc.table.tables.records.TProjectRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TProject extends TableImpl<TProjectRecord> {

    private static final long serialVersionUID = 599681894;

    /**
     * The reference instance of <code>kelu.t_project</code>
     */
    public static final TProject t_project = new TProject();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TProjectRecord> getRecordType() {
        return TProjectRecord.class;
    }

    /**
     * The column <code>kelu.t_project.id</code>.
     */
    public final TableField<TProjectRecord, Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>kelu.t_project.project_name</code>.
     */
    public final TableField<TProjectRecord, String> project_name = createField("project_name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kelu.t_project.link</code>.
     */
    public final TableField<TProjectRecord, String> link = createField("link", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>kelu.t_project.parent_id</code>.
     */
    public final TableField<TProjectRecord, Integer> parent_id = createField("parent_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>kelu.t_project.level</code>.
     */
    public final TableField<TProjectRecord, Integer> level = createField("level", org.jooq.impl.SQLDataType.INTEGER.defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>kelu.t_project.create_time</code>.
     */
    public final TableField<TProjectRecord, LocalDateTime> create_time = createField("create_time", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>kelu.t_project</code> table reference
     */
    public TProject() {
        this(DSL.name("t_project"), null);
    }

    /**
     * Create an aliased <code>kelu.t_project</code> table reference
     */
    public TProject(String alias) {
        this(DSL.name(alias), t_project);
    }

    /**
     * Create an aliased <code>kelu.t_project</code> table reference
     */
    public TProject(Name alias) {
        this(alias, t_project);
    }

    private TProject(Name alias, Table<TProjectRecord> aliased) {
        this(alias, aliased, null);
    }

    private TProject(Name alias, Table<TProjectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kelu.kelu;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TProjectRecord, Integer> getIdentity() {
        return Keys.IDENTITY_t_project;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TProjectRecord> getPrimaryKey() {
        return Keys.KEY_t_project_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TProjectRecord>> getKeys() {
        return Arrays.<UniqueKey<TProjectRecord>>asList(Keys.KEY_t_project_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProject as(String alias) {
        return new TProject(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProject as(Name alias) {
        return new TProject(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TProject rename(String name) {
        return new TProject(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TProject rename(Name name) {
        return new TProject(name, null);
    }
}
