/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables;


import com.example.mvc.table.Kelu;
import com.example.mvc.table.Keys;
import com.example.mvc.table.tables.records.TRecheckRecordRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 房间复查记录表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRecheckRecord extends TableImpl<TRecheckRecordRecord> {

    private static final long serialVersionUID = 99382981;

    /**
     * The reference instance of <code>kelu.t_recheck_record</code>
     */
    public static final TRecheckRecord t_recheck_record = new TRecheckRecord();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TRecheckRecordRecord> getRecordType() {
        return TRecheckRecordRecord.class;
    }

    /**
     * The column <code>kelu.t_recheck_record.id</code>.
     */
    public final TableField<TRecheckRecordRecord, Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>kelu.t_recheck_record.group_leader_id</code>. 组长Id
     */
    public final TableField<TRecheckRecordRecord, Integer> group_leader_id = createField("group_leader_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "组长Id");

    /**
     * The column <code>kelu.t_recheck_record.account_id</code>. 组员Id
     */
    public final TableField<TRecheckRecordRecord, Integer> account_id = createField("account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "组员Id");

    /**
     * The column <code>kelu.t_recheck_record.room_id</code>. 房间Id
     */
    public final TableField<TRecheckRecordRecord, Integer> room_id = createField("room_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "房间Id");

    /**
     * The column <code>kelu.t_recheck_record.room_member_id</code>. 用户Id
     */
    public final TableField<TRecheckRecordRecord, Integer> room_member_id = createField("room_member_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "用户Id");

    /**
     * The column <code>kelu.t_recheck_record.post_time</code>. 复查时间
     */
    public final TableField<TRecheckRecordRecord, LocalDateTime> post_time = createField("post_time", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "复查时间");

    /**
     * The column <code>kelu.t_recheck_record.status</code>. 审核结果:0 没有审核 1 警告 2 封禁用户  3 私信 4  解封用户 5 标记合格
     */
    public final TableField<TRecheckRecordRecord, Byte> status = createField("status", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "审核结果:0 没有审核 1 警告 2 封禁用户  3 私信 4  解封用户 5 标记合格");

    /**
     * The column <code>kelu.t_recheck_record.live_resolve_id</code>. 违规记录Id
     */
    public final TableField<TRecheckRecordRecord, Integer> live_resolve_id = createField("live_resolve_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "违规记录Id");

    /**
     * Create a <code>kelu.t_recheck_record</code> table reference
     */
    public TRecheckRecord() {
        this(DSL.name("t_recheck_record"), null);
    }

    /**
     * Create an aliased <code>kelu.t_recheck_record</code> table reference
     */
    public TRecheckRecord(String alias) {
        this(DSL.name(alias), t_recheck_record);
    }

    /**
     * Create an aliased <code>kelu.t_recheck_record</code> table reference
     */
    public TRecheckRecord(Name alias) {
        this(alias, t_recheck_record);
    }

    private TRecheckRecord(Name alias, Table<TRecheckRecordRecord> aliased) {
        this(alias, aliased, null);
    }

    private TRecheckRecord(Name alias, Table<TRecheckRecordRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "房间复查记录表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kelu.kelu;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TRecheckRecordRecord, Integer> getIdentity() {
        return Keys.IDENTITY_t_recheck_record;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TRecheckRecordRecord> getPrimaryKey() {
        return Keys.KEY_t_recheck_record_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TRecheckRecordRecord>> getKeys() {
        return Arrays.<UniqueKey<TRecheckRecordRecord>>asList(Keys.KEY_t_recheck_record_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRecheckRecord as(String alias) {
        return new TRecheckRecord(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRecheckRecord as(Name alias) {
        return new TRecheckRecord(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TRecheckRecord rename(String name) {
        return new TRecheckRecord(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TRecheckRecord rename(Name name) {
        return new TRecheckRecord(name, null);
    }
}
