/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables;


import com.example.mvc.table.Kelu;
import com.example.mvc.table.Keys;
import com.example.mvc.table.tables.records.TRoleAccountRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRoleAccount extends TableImpl<TRoleAccountRecord> {

    private static final long serialVersionUID = 1325039366;

    /**
     * The reference instance of <code>kelu.t_role_account</code>
     */
    public static final TRoleAccount t_role_account = new TRoleAccount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TRoleAccountRecord> getRecordType() {
        return TRoleAccountRecord.class;
    }

    /**
     * The column <code>kelu.t_role_account.id</code>.
     */
    public final TableField<TRoleAccountRecord, Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>kelu.t_role_account.role_id</code>.
     */
    public final TableField<TRoleAccountRecord, Integer> role_id = createField("role_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>kelu.t_role_account.account_id</code>.
     */
    public final TableField<TRoleAccountRecord, Integer> account_id = createField("account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>kelu.t_role_account</code> table reference
     */
    public TRoleAccount() {
        this(DSL.name("t_role_account"), null);
    }

    /**
     * Create an aliased <code>kelu.t_role_account</code> table reference
     */
    public TRoleAccount(String alias) {
        this(DSL.name(alias), t_role_account);
    }

    /**
     * Create an aliased <code>kelu.t_role_account</code> table reference
     */
    public TRoleAccount(Name alias) {
        this(alias, t_role_account);
    }

    private TRoleAccount(Name alias, Table<TRoleAccountRecord> aliased) {
        this(alias, aliased, null);
    }

    private TRoleAccount(Name alias, Table<TRoleAccountRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kelu.kelu;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TRoleAccountRecord, Integer> getIdentity() {
        return Keys.IDENTITY_t_role_account;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TRoleAccountRecord> getPrimaryKey() {
        return Keys.KEY_t_role_account_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TRoleAccountRecord>> getKeys() {
        return Arrays.<UniqueKey<TRoleAccountRecord>>asList(Keys.KEY_t_role_account_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoleAccount as(String alias) {
        return new TRoleAccount(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoleAccount as(Name alias) {
        return new TRoleAccount(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TRoleAccount rename(String name) {
        return new TRoleAccount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TRoleAccount rename(Name name) {
        return new TRoleAccount(name, null);
    }
}
