/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables;


import com.example.mvc.table.Kelu;
import com.example.mvc.table.Keys;
import com.example.mvc.table.tables.records.TRoleProjectRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRoleProject extends TableImpl<TRoleProjectRecord> {

    private static final long serialVersionUID = -1842013768;

    /**
     * The reference instance of <code>kelu.t_role_project</code>
     */
    public static final TRoleProject t_role_project = new TRoleProject();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TRoleProjectRecord> getRecordType() {
        return TRoleProjectRecord.class;
    }

    /**
     * The column <code>kelu.t_role_project.id</code>.
     */
    public final TableField<TRoleProjectRecord, Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>kelu.t_role_project.role_id</code>.
     */
    public final TableField<TRoleProjectRecord, Integer> role_id = createField("role_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>kelu.t_role_project.project_id</code>.
     */
    public final TableField<TRoleProjectRecord, Integer> project_id = createField("project_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>kelu.t_role_project</code> table reference
     */
    public TRoleProject() {
        this(DSL.name("t_role_project"), null);
    }

    /**
     * Create an aliased <code>kelu.t_role_project</code> table reference
     */
    public TRoleProject(String alias) {
        this(DSL.name(alias), t_role_project);
    }

    /**
     * Create an aliased <code>kelu.t_role_project</code> table reference
     */
    public TRoleProject(Name alias) {
        this(alias, t_role_project);
    }

    private TRoleProject(Name alias, Table<TRoleProjectRecord> aliased) {
        this(alias, aliased, null);
    }

    private TRoleProject(Name alias, Table<TRoleProjectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kelu.kelu;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TRoleProjectRecord, Integer> getIdentity() {
        return Keys.IDENTITY_t_role_project;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TRoleProjectRecord> getPrimaryKey() {
        return Keys.KEY_t_role_project_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TRoleProjectRecord>> getKeys() {
        return Arrays.<UniqueKey<TRoleProjectRecord>>asList(Keys.KEY_t_role_project_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoleProject as(String alias) {
        return new TRoleProject(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoleProject as(Name alias) {
        return new TRoleProject(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TRoleProject rename(String name) {
        return new TRoleProject(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TRoleProject rename(Name name) {
        return new TRoleProject(name, null);
    }
}
