/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables;


import com.example.mvc.table.Kelu;
import com.example.mvc.table.Keys;
import com.example.mvc.table.tables.records.TRoomMemberCheckRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRoomMemberCheck extends TableImpl<TRoomMemberCheckRecord> {

    private static final long serialVersionUID = -893421349;

    /**
     * The reference instance of <code>kelu.t_room_member_check</code>
     */
    public static final TRoomMemberCheck t_room_member_check = new TRoomMemberCheck();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TRoomMemberCheckRecord> getRecordType() {
        return TRoomMemberCheckRecord.class;
    }

    /**
     * The column <code>kelu.t_room_member_check.id</code>.
     */
    public final TableField<TRoomMemberCheckRecord, Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>kelu.t_room_member_check.room_id</code>.
     */
    public final TableField<TRoomMemberCheckRecord, Integer> room_id = createField("room_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kelu.t_room_member_check.user_id</code>.
     */
    public final TableField<TRoomMemberCheckRecord, Integer> user_id = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kelu.t_room_member_check.postTime</code>.
     */
    public final TableField<TRoomMemberCheckRecord, LocalDateTime> postTime = createField("postTime", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>kelu.t_room_member_check.account_id</code>.
     */
    public final TableField<TRoomMemberCheckRecord, Integer> account_id = createField("account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>kelu.t_room_member_check</code> table reference
     */
    public TRoomMemberCheck() {
        this(DSL.name("t_room_member_check"), null);
    }

    /**
     * Create an aliased <code>kelu.t_room_member_check</code> table reference
     */
    public TRoomMemberCheck(String alias) {
        this(DSL.name(alias), t_room_member_check);
    }

    /**
     * Create an aliased <code>kelu.t_room_member_check</code> table reference
     */
    public TRoomMemberCheck(Name alias) {
        this(alias, t_room_member_check);
    }

    private TRoomMemberCheck(Name alias, Table<TRoomMemberCheckRecord> aliased) {
        this(alias, aliased, null);
    }

    private TRoomMemberCheck(Name alias, Table<TRoomMemberCheckRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kelu.kelu;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TRoomMemberCheckRecord, Integer> getIdentity() {
        return Keys.IDENTITY_t_room_member_check;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TRoomMemberCheckRecord> getPrimaryKey() {
        return Keys.KEY_t_room_member_check_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TRoomMemberCheckRecord>> getKeys() {
        return Arrays.<UniqueKey<TRoomMemberCheckRecord>>asList(Keys.KEY_t_room_member_check_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomMemberCheck as(String alias) {
        return new TRoomMemberCheck(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomMemberCheck as(Name alias) {
        return new TRoomMemberCheck(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TRoomMemberCheck rename(String name) {
        return new TRoomMemberCheck(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TRoomMemberCheck rename(Name name) {
        return new TRoomMemberCheck(name, null);
    }
}
