/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables;


import com.example.mvc.table.Kelu;
import com.example.mvc.table.Keys;
import com.example.mvc.table.tables.records.TTopicAttributeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTopicAttribute extends TableImpl<TTopicAttributeRecord> {

    private static final long serialVersionUID = -1327649088;

    /**
     * The reference instance of <code>kelu.t_topic_attribute</code>
     */
    public static final TTopicAttribute t_topic_attribute = new TTopicAttribute();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TTopicAttributeRecord> getRecordType() {
        return TTopicAttributeRecord.class;
    }

    /**
     * The column <code>kelu.t_topic_attribute.id</code>.
     */
    public final TableField<TTopicAttributeRecord, Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>kelu.t_topic_attribute.topic_id</code>. 话题id
     */
    public final TableField<TTopicAttributeRecord, Integer> topic_id = createField("topic_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "话题id");

    /**
     * The column <code>kelu.t_topic_attribute.gender</code>. 0：男 1：女
     */
    public final TableField<TTopicAttributeRecord, Byte> gender = createField("gender", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "0：男 1：女");

    /**
     * The column <code>kelu.t_topic_attribute.age</code>. 年龄段 0：&lt;= 11岁 ; 1: 12~14岁; 2: 15~17岁; 3: 18~24岁; 4: 25~28岁; 5: 28岁以上
     */
    public final TableField<TTopicAttributeRecord, Byte> age = createField("age", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "年龄段 0：<= 11岁 ; 1: 12~14岁; 2: 15~17岁; 3: 18~24岁; 4: 25~28岁; 5: 28岁以上");

    /**
     * The column <code>kelu.t_topic_attribute.categoryIDs</code>. 学习标签 最大为3个
     */
    public final TableField<TTopicAttributeRecord, String> categoryIDs = createField("categoryIDs", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "学习标签 最大为3个");

    /**
     * The column <code>kelu.t_topic_attribute.is_hot</code>. 是否热门 0 为 普通  1为热门
     */
    public final TableField<TTopicAttributeRecord, Byte> is_hot = createField("is_hot", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "是否热门 0 为 普通  1为热门");

    /**
     * The column <code>kelu.t_topic_attribute.is_old</code>.
     */
    public final TableField<TTopicAttributeRecord, Byte> is_old = createField("is_old", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * Create a <code>kelu.t_topic_attribute</code> table reference
     */
    public TTopicAttribute() {
        this(DSL.name("t_topic_attribute"), null);
    }

    /**
     * Create an aliased <code>kelu.t_topic_attribute</code> table reference
     */
    public TTopicAttribute(String alias) {
        this(DSL.name(alias), t_topic_attribute);
    }

    /**
     * Create an aliased <code>kelu.t_topic_attribute</code> table reference
     */
    public TTopicAttribute(Name alias) {
        this(alias, t_topic_attribute);
    }

    private TTopicAttribute(Name alias, Table<TTopicAttributeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TTopicAttribute(Name alias, Table<TTopicAttributeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kelu.kelu;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TTopicAttributeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_t_topic_attribute;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TTopicAttributeRecord> getPrimaryKey() {
        return Keys.KEY_t_topic_attribute_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TTopicAttributeRecord>> getKeys() {
        return Arrays.<UniqueKey<TTopicAttributeRecord>>asList(Keys.KEY_t_topic_attribute_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTopicAttribute as(String alias) {
        return new TTopicAttribute(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTopicAttribute as(Name alias) {
        return new TTopicAttribute(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TTopicAttribute rename(String name) {
        return new TTopicAttribute(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TTopicAttribute rename(Name name) {
        return new TTopicAttribute(name, null);
    }
}
