/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables;


import com.example.mvc.table.Kelu;
import com.example.mvc.table.Keys;
import com.example.mvc.table.tables.records.TUserMessageRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserMessage extends TableImpl<TUserMessageRecord> {

    private static final long serialVersionUID = -660036561;

    /**
     * The reference instance of <code>kelu.t_user_message</code>
     */
    public static final TUserMessage t_user_message = new TUserMessage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TUserMessageRecord> getRecordType() {
        return TUserMessageRecord.class;
    }

    /**
     * The column <code>kelu.t_user_message.id</code>.
     */
    public final TableField<TUserMessageRecord, Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>kelu.t_user_message.userID</code>.
     */
    public final TableField<TUserMessageRecord, Integer> userID = createField("userID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kelu.t_user_message.content</code>.
     */
    public final TableField<TUserMessageRecord, String> content = createField("content", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>kelu.t_user_message.post_time</code>.
     */
    public final TableField<TUserMessageRecord, LocalDateTime> post_time = createField("post_time", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>kelu.t_user_message</code> table reference
     */
    public TUserMessage() {
        this(DSL.name("t_user_message"), null);
    }

    /**
     * Create an aliased <code>kelu.t_user_message</code> table reference
     */
    public TUserMessage(String alias) {
        this(DSL.name(alias), t_user_message);
    }

    /**
     * Create an aliased <code>kelu.t_user_message</code> table reference
     */
    public TUserMessage(Name alias) {
        this(alias, t_user_message);
    }

    private TUserMessage(Name alias, Table<TUserMessageRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUserMessage(Name alias, Table<TUserMessageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kelu.kelu;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TUserMessageRecord, Integer> getIdentity() {
        return Keys.IDENTITY_t_user_message;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TUserMessageRecord> getPrimaryKey() {
        return Keys.KEY_t_user_message_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TUserMessageRecord>> getKeys() {
        return Arrays.<UniqueKey<TUserMessageRecord>>asList(Keys.KEY_t_user_message_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserMessage as(String alias) {
        return new TUserMessage(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserMessage as(Name alias) {
        return new TUserMessage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserMessage rename(String name) {
        return new TUserMessage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserMessage rename(Name name) {
        return new TUserMessage(name, null);
    }
}
