/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccountOperateRecord implements Serializable {

    private static final long serialVersionUID = 1141021666;

    private Integer       id;
    private Integer       accountId;
    private Integer       relateId;
    private Short         type;
    private LocalDateTime createTime;
    private String        operateInfo;

    public TAccountOperateRecord() {}

    public TAccountOperateRecord(TAccountOperateRecord value) {
        this.id = value.id;
        this.accountId = value.accountId;
        this.relateId = value.relateId;
        this.type = value.type;
        this.createTime = value.createTime;
        this.operateInfo = value.operateInfo;
    }

    public TAccountOperateRecord(
        Integer       id,
        Integer       accountId,
        Integer       relateId,
        Short         type,
        LocalDateTime createTime,
        String        operateInfo
    ) {
        this.id = id;
        this.accountId = accountId;
        this.relateId = relateId;
        this.type = type;
        this.createTime = createTime;
        this.operateInfo = operateInfo;
    }

    public Integer getId() {
        return this.id;
    }

    public TAccountOperateRecord setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getAccountId() {
        return this.accountId;
    }

    public TAccountOperateRecord setAccountId(Integer accountId) {
        this.accountId = accountId;
        return this;
    }

    @NotNull
    public Integer getRelateId() {
        return this.relateId;
    }

    public TAccountOperateRecord setRelateId(Integer relateId) {
        this.relateId = relateId;
        return this;
    }

    @NotNull
    public Short getType() {
        return this.type;
    }

    public TAccountOperateRecord setType(Short type) {
        this.type = type;
        return this;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public TAccountOperateRecord setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    @NotNull
    @Size(max = 1024)
    public String getOperateInfo() {
        return this.operateInfo;
    }

    public TAccountOperateRecord setOperateInfo(String operateInfo) {
        this.operateInfo = operateInfo;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TAccountOperateRecord other = (TAccountOperateRecord) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!accountId.equals(other.accountId))
            return false;
        if (relateId == null) {
            if (other.relateId != null)
                return false;
        }
        else if (!relateId.equals(other.relateId))
            return false;
        if (type == null) {
            if (other.type != null)
                return false;
        }
        else if (!type.equals(other.type))
            return false;
        if (createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!createTime.equals(other.createTime))
            return false;
        if (operateInfo == null) {
            if (other.operateInfo != null)
                return false;
        }
        else if (!operateInfo.equals(other.operateInfo))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        result = prime * result + ((this.relateId == null) ? 0 : this.relateId.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.operateInfo == null) ? 0 : this.operateInfo.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TAccountOperateRecord (");

        sb.append(id);
        sb.append(", ").append(accountId);
        sb.append(", ").append(relateId);
        sb.append(", ").append(type);
        sb.append(", ").append(createTime);
        sb.append(", ").append(operateInfo);

        sb.append(")");
        return sb.toString();
    }
}
