/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * 用户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccount implements Serializable {

    private static final long serialVersionUID = -1608016587;

    private Integer       id;
    private String        username;
    private String        password;
    private LocalDateTime createTime;
    private LocalDateTime lastTime;
    private Byte          isAdmin;
    private Integer       departmentId;
    private String        nickname;
    private Byte          isDisabled;

    public TAccount() {}

    public TAccount(TAccount value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.createTime = value.createTime;
        this.lastTime = value.lastTime;
        this.isAdmin = value.isAdmin;
        this.departmentId = value.departmentId;
        this.nickname = value.nickname;
        this.isDisabled = value.isDisabled;
    }

    public TAccount(
        Integer       id,
        String        username,
        String        password,
        LocalDateTime createTime,
        LocalDateTime lastTime,
        Byte          isAdmin,
        Integer       departmentId,
        String        nickname,
        Byte          isDisabled
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.createTime = createTime;
        this.lastTime = lastTime;
        this.isAdmin = isAdmin;
        this.departmentId = departmentId;
        this.nickname = nickname;
        this.isDisabled = isDisabled;
    }

    public Integer getId() {
        return this.id;
    }

    public TAccount setId(Integer id) {
        this.id = id;
        return this;
    }

    @Size(max = 255)
    public String getUsername() {
        return this.username;
    }

    public TAccount setUsername(String username) {
        this.username = username;
        return this;
    }

    @Size(max = 255)
    public String getPassword() {
        return this.password;
    }

    public TAccount setPassword(String password) {
        this.password = password;
        return this;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public TAccount setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    public LocalDateTime getLastTime() {
        return this.lastTime;
    }

    public TAccount setLastTime(LocalDateTime lastTime) {
        this.lastTime = lastTime;
        return this;
    }

    public Byte getIsAdmin() {
        return this.isAdmin;
    }

    public TAccount setIsAdmin(Byte isAdmin) {
        this.isAdmin = isAdmin;
        return this;
    }

    public Integer getDepartmentId() {
        return this.departmentId;
    }

    public TAccount setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
        return this;
    }

    @NotNull
    @Size(max = 255)
    public String getNickname() {
        return this.nickname;
    }

    public TAccount setNickname(String nickname) {
        this.nickname = nickname;
        return this;
    }

    public Byte getIsDisabled() {
        return this.isDisabled;
    }

    public TAccount setIsDisabled(Byte isDisabled) {
        this.isDisabled = isDisabled;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TAccount other = (TAccount) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (username == null) {
            if (other.username != null)
                return false;
        }
        else if (!username.equals(other.username))
            return false;
        if (password == null) {
            if (other.password != null)
                return false;
        }
        else if (!password.equals(other.password))
            return false;
        if (createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!createTime.equals(other.createTime))
            return false;
        if (lastTime == null) {
            if (other.lastTime != null)
                return false;
        }
        else if (!lastTime.equals(other.lastTime))
            return false;
        if (isAdmin == null) {
            if (other.isAdmin != null)
                return false;
        }
        else if (!isAdmin.equals(other.isAdmin))
            return false;
        if (departmentId == null) {
            if (other.departmentId != null)
                return false;
        }
        else if (!departmentId.equals(other.departmentId))
            return false;
        if (nickname == null) {
            if (other.nickname != null)
                return false;
        }
        else if (!nickname.equals(other.nickname))
            return false;
        if (isDisabled == null) {
            if (other.isDisabled != null)
                return false;
        }
        else if (!isDisabled.equals(other.isDisabled))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.lastTime == null) ? 0 : this.lastTime.hashCode());
        result = prime * result + ((this.isAdmin == null) ? 0 : this.isAdmin.hashCode());
        result = prime * result + ((this.departmentId == null) ? 0 : this.departmentId.hashCode());
        result = prime * result + ((this.nickname == null) ? 0 : this.nickname.hashCode());
        result = prime * result + ((this.isDisabled == null) ? 0 : this.isDisabled.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TAccount (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(createTime);
        sb.append(", ").append(lastTime);
        sb.append(", ").append(isAdmin);
        sb.append(", ").append(departmentId);
        sb.append(", ").append(nickname);
        sb.append(", ").append(isDisabled);

        sb.append(")");
        return sb.toString();
    }
}
