/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccountBindingUser implements Serializable {

    private static final long serialVersionUID = -1035997631;

    private Integer       id;
    private Integer       accountId;
    private Integer       userId;
    private Byte          isRemove;
    private LocalDateTime bindingTime;

    public TAccountBindingUser() {}

    public TAccountBindingUser(TAccountBindingUser value) {
        this.id = value.id;
        this.accountId = value.accountId;
        this.userId = value.userId;
        this.isRemove = value.isRemove;
        this.bindingTime = value.bindingTime;
    }

    public TAccountBindingUser(
        Integer       id,
        Integer       accountId,
        Integer       userId,
        Byte          isRemove,
        LocalDateTime bindingTime
    ) {
        this.id = id;
        this.accountId = accountId;
        this.userId = userId;
        this.isRemove = isRemove;
        this.bindingTime = bindingTime;
    }

    public Integer getId() {
        return this.id;
    }

    public TAccountBindingUser setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    public Integer getAccountId() {
        return this.accountId;
    }

    public TAccountBindingUser setAccountId(Integer accountId) {
        this.accountId = accountId;
        return this;
    }

    @NotNull
    public Integer getUserId() {
        return this.userId;
    }

    public TAccountBindingUser setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    @NotNull
    public Byte getIsRemove() {
        return this.isRemove;
    }

    public TAccountBindingUser setIsRemove(Byte isRemove) {
        this.isRemove = isRemove;
        return this;
    }

    public LocalDateTime getBindingTime() {
        return this.bindingTime;
    }

    public TAccountBindingUser setBindingTime(LocalDateTime bindingTime) {
        this.bindingTime = bindingTime;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TAccountBindingUser other = (TAccountBindingUser) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!accountId.equals(other.accountId))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (isRemove == null) {
            if (other.isRemove != null)
                return false;
        }
        else if (!isRemove.equals(other.isRemove))
            return false;
        if (bindingTime == null) {
            if (other.bindingTime != null)
                return false;
        }
        else if (!bindingTime.equals(other.bindingTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.isRemove == null) ? 0 : this.isRemove.hashCode());
        result = prime * result + ((this.bindingTime == null) ? 0 : this.bindingTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TAccountBindingUser (");

        sb.append(id);
        sb.append(", ").append(accountId);
        sb.append(", ").append(userId);
        sb.append(", ").append(isRemove);
        sb.append(", ").append(bindingTime);

        sb.append(")");
        return sb.toString();
    }
}
