/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBigvVerifyRecord implements Serializable {

    private static final long serialVersionUID = 1371185231;

    private Integer       id;
    private Integer       userId;
    private Integer       accountId;
    private Byte          status;
    private LocalDateTime postTime;

    public TBigvVerifyRecord() {}

    public TBigvVerifyRecord(TBigvVerifyRecord value) {
        this.id = value.id;
        this.userId = value.userId;
        this.accountId = value.accountId;
        this.status = value.status;
        this.postTime = value.postTime;
    }

    public TBigvVerifyRecord(
        Integer       id,
        Integer       userId,
        Integer       accountId,
        Byte          status,
        LocalDateTime postTime
    ) {
        this.id = id;
        this.userId = userId;
        this.accountId = accountId;
        this.status = status;
        this.postTime = postTime;
    }

    public Integer getId() {
        return this.id;
    }

    public TBigvVerifyRecord setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    public Integer getUserId() {
        return this.userId;
    }

    public TBigvVerifyRecord setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    @NotNull
    public Integer getAccountId() {
        return this.accountId;
    }

    public TBigvVerifyRecord setAccountId(Integer accountId) {
        this.accountId = accountId;
        return this;
    }

    public Byte getStatus() {
        return this.status;
    }

    public TBigvVerifyRecord setStatus(Byte status) {
        this.status = status;
        return this;
    }

    public LocalDateTime getPostTime() {
        return this.postTime;
    }

    public TBigvVerifyRecord setPostTime(LocalDateTime postTime) {
        this.postTime = postTime;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TBigvVerifyRecord other = (TBigvVerifyRecord) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!accountId.equals(other.accountId))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (postTime == null) {
            if (other.postTime != null)
                return false;
        }
        else if (!postTime.equals(other.postTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.postTime == null) ? 0 : this.postTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TBigvVerifyRecord (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(accountId);
        sb.append(", ").append(status);
        sb.append(", ").append(postTime);

        sb.append(")");
        return sb.toString();
    }
}
