/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDayLabelSumRecord implements Serializable {

    private static final long serialVersionUID = -544469847;

    private Integer       id;
    private Integer       accountId;
    private LocalDateTime startTime;
    private LocalDateTime endTime;
    private Long          date;
    private Integer       labelCount;

    public TDayLabelSumRecord() {}

    public TDayLabelSumRecord(TDayLabelSumRecord value) {
        this.id = value.id;
        this.accountId = value.accountId;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
        this.date = value.date;
        this.labelCount = value.labelCount;
    }

    public TDayLabelSumRecord(
        Integer       id,
        Integer       accountId,
        LocalDateTime startTime,
        LocalDateTime endTime,
        Long          date,
        Integer       labelCount
    ) {
        this.id = id;
        this.accountId = accountId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.date = date;
        this.labelCount = labelCount;
    }

    public Integer getId() {
        return this.id;
    }

    public TDayLabelSumRecord setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    public Integer getAccountId() {
        return this.accountId;
    }

    public TDayLabelSumRecord setAccountId(Integer accountId) {
        this.accountId = accountId;
        return this;
    }

    public LocalDateTime getStartTime() {
        return this.startTime;
    }

    public TDayLabelSumRecord setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
        return this;
    }

    public LocalDateTime getEndTime() {
        return this.endTime;
    }

    public TDayLabelSumRecord setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
        return this;
    }

    public Long getDate() {
        return this.date;
    }

    public TDayLabelSumRecord setDate(Long date) {
        this.date = date;
        return this;
    }

    public Integer getLabelCount() {
        return this.labelCount;
    }

    public TDayLabelSumRecord setLabelCount(Integer labelCount) {
        this.labelCount = labelCount;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TDayLabelSumRecord other = (TDayLabelSumRecord) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!accountId.equals(other.accountId))
            return false;
        if (startTime == null) {
            if (other.startTime != null)
                return false;
        }
        else if (!startTime.equals(other.startTime))
            return false;
        if (endTime == null) {
            if (other.endTime != null)
                return false;
        }
        else if (!endTime.equals(other.endTime))
            return false;
        if (date == null) {
            if (other.date != null)
                return false;
        }
        else if (!date.equals(other.date))
            return false;
        if (labelCount == null) {
            if (other.labelCount != null)
                return false;
        }
        else if (!labelCount.equals(other.labelCount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        result = prime * result + ((this.startTime == null) ? 0 : this.startTime.hashCode());
        result = prime * result + ((this.endTime == null) ? 0 : this.endTime.hashCode());
        result = prime * result + ((this.date == null) ? 0 : this.date.hashCode());
        result = prime * result + ((this.labelCount == null) ? 0 : this.labelCount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TDayLabelSumRecord (");

        sb.append(id);
        sb.append(", ").append(accountId);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);
        sb.append(", ").append(date);
        sb.append(", ").append(labelCount);

        sb.append(")");
        return sb.toString();
    }
}
