/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDepartment implements Serializable {

    private static final long serialVersionUID = 360931361;

    private Integer       id;
    private String        departmentName;
    private LocalDateTime createTime;
    private Integer       parentId;
    private Integer       seq;
    private Byte          level;
    private Byte          isUsed;
    private String        departmentDescribe;

    public TDepartment() {}

    public TDepartment(TDepartment value) {
        this.id = value.id;
        this.departmentName = value.departmentName;
        this.createTime = value.createTime;
        this.parentId = value.parentId;
        this.seq = value.seq;
        this.level = value.level;
        this.isUsed = value.isUsed;
        this.departmentDescribe = value.departmentDescribe;
    }

    public TDepartment(
        Integer       id,
        String        departmentName,
        LocalDateTime createTime,
        Integer       parentId,
        Integer       seq,
        Byte          level,
        Byte          isUsed,
        String        departmentDescribe
    ) {
        this.id = id;
        this.departmentName = departmentName;
        this.createTime = createTime;
        this.parentId = parentId;
        this.seq = seq;
        this.level = level;
        this.isUsed = isUsed;
        this.departmentDescribe = departmentDescribe;
    }

    public Integer getId() {
        return this.id;
    }

    public TDepartment setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    @Size(max = 255)
    public String getDepartmentName() {
        return this.departmentName;
    }

    public TDepartment setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
        return this;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public TDepartment setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    public Integer getParentId() {
        return this.parentId;
    }

    public TDepartment setParentId(Integer parentId) {
        this.parentId = parentId;
        return this;
    }

    @NotNull
    public Integer getSeq() {
        return this.seq;
    }

    public TDepartment setSeq(Integer seq) {
        this.seq = seq;
        return this;
    }

    @NotNull
    public Byte getLevel() {
        return this.level;
    }

    public TDepartment setLevel(Byte level) {
        this.level = level;
        return this;
    }

    public Byte getIsUsed() {
        return this.isUsed;
    }

    public TDepartment setIsUsed(Byte isUsed) {
        this.isUsed = isUsed;
        return this;
    }

    @NotNull
    @Size(max = 255)
    public String getDepartmentDescribe() {
        return this.departmentDescribe;
    }

    public TDepartment setDepartmentDescribe(String departmentDescribe) {
        this.departmentDescribe = departmentDescribe;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TDepartment other = (TDepartment) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (departmentName == null) {
            if (other.departmentName != null)
                return false;
        }
        else if (!departmentName.equals(other.departmentName))
            return false;
        if (createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!createTime.equals(other.createTime))
            return false;
        if (parentId == null) {
            if (other.parentId != null)
                return false;
        }
        else if (!parentId.equals(other.parentId))
            return false;
        if (seq == null) {
            if (other.seq != null)
                return false;
        }
        else if (!seq.equals(other.seq))
            return false;
        if (level == null) {
            if (other.level != null)
                return false;
        }
        else if (!level.equals(other.level))
            return false;
        if (isUsed == null) {
            if (other.isUsed != null)
                return false;
        }
        else if (!isUsed.equals(other.isUsed))
            return false;
        if (departmentDescribe == null) {
            if (other.departmentDescribe != null)
                return false;
        }
        else if (!departmentDescribe.equals(other.departmentDescribe))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.departmentName == null) ? 0 : this.departmentName.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.parentId == null) ? 0 : this.parentId.hashCode());
        result = prime * result + ((this.seq == null) ? 0 : this.seq.hashCode());
        result = prime * result + ((this.level == null) ? 0 : this.level.hashCode());
        result = prime * result + ((this.isUsed == null) ? 0 : this.isUsed.hashCode());
        result = prime * result + ((this.departmentDescribe == null) ? 0 : this.departmentDescribe.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TDepartment (");

        sb.append(id);
        sb.append(", ").append(departmentName);
        sb.append(", ").append(createTime);
        sb.append(", ").append(parentId);
        sb.append(", ").append(seq);
        sb.append(", ").append(level);
        sb.append(", ").append(isUsed);
        sb.append(", ").append(departmentDescribe);

        sb.append(")");
        return sb.toString();
    }
}
