/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TFeedLabelRecord implements Serializable {

    private static final long serialVersionUID = -522732797;

    private Integer       id;
    private Integer       feedId;
    private Integer       accountId;
    private LocalDateTime postTime;
    private Byte          status;

    public TFeedLabelRecord() {}

    public TFeedLabelRecord(TFeedLabelRecord value) {
        this.id = value.id;
        this.feedId = value.feedId;
        this.accountId = value.accountId;
        this.postTime = value.postTime;
        this.status = value.status;
    }

    public TFeedLabelRecord(
        Integer       id,
        Integer       feedId,
        Integer       accountId,
        LocalDateTime postTime,
        Byte          status
    ) {
        this.id = id;
        this.feedId = feedId;
        this.accountId = accountId;
        this.postTime = postTime;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public TFeedLabelRecord setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    public Integer getFeedId() {
        return this.feedId;
    }

    public TFeedLabelRecord setFeedId(Integer feedId) {
        this.feedId = feedId;
        return this;
    }

    public Integer getAccountId() {
        return this.accountId;
    }

    public TFeedLabelRecord setAccountId(Integer accountId) {
        this.accountId = accountId;
        return this;
    }

    public LocalDateTime getPostTime() {
        return this.postTime;
    }

    public TFeedLabelRecord setPostTime(LocalDateTime postTime) {
        this.postTime = postTime;
        return this;
    }

    public Byte getStatus() {
        return this.status;
    }

    public TFeedLabelRecord setStatus(Byte status) {
        this.status = status;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TFeedLabelRecord other = (TFeedLabelRecord) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (feedId == null) {
            if (other.feedId != null)
                return false;
        }
        else if (!feedId.equals(other.feedId))
            return false;
        if (accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!accountId.equals(other.accountId))
            return false;
        if (postTime == null) {
            if (other.postTime != null)
                return false;
        }
        else if (!postTime.equals(other.postTime))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.feedId == null) ? 0 : this.feedId.hashCode());
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        result = prime * result + ((this.postTime == null) ? 0 : this.postTime.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TFeedLabelRecord (");

        sb.append(id);
        sb.append(", ").append(feedId);
        sb.append(", ").append(accountId);
        sb.append(", ").append(postTime);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
