/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOperateCategory implements Serializable {

    private static final long serialVersionUID = 1153814510;

    private Integer id;
    private String  categoryName;

    public TOperateCategory() {}

    public TOperateCategory(TOperateCategory value) {
        this.id = value.id;
        this.categoryName = value.categoryName;
    }

    public TOperateCategory(
        Integer id,
        String  categoryName
    ) {
        this.id = id;
        this.categoryName = categoryName;
    }

    public Integer getId() {
        return this.id;
    }

    public TOperateCategory setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    @Size(max = 255)
    public String getCategoryName() {
        return this.categoryName;
    }

    public TOperateCategory setCategoryName(String categoryName) {
        this.categoryName = categoryName;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TOperateCategory other = (TOperateCategory) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (categoryName == null) {
            if (other.categoryName != null)
                return false;
        }
        else if (!categoryName.equals(other.categoryName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.categoryName == null) ? 0 : this.categoryName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TOperateCategory (");

        sb.append(id);
        sb.append(", ").append(categoryName);

        sb.append(")");
        return sb.toString();
    }
}
