/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOperate implements Serializable {

    private static final long serialVersionUID = -1337799970;

    private Integer id;
    private String  operateName;
    private Integer categoryId;
    private Byte    isDelete;

    public TOperate() {}

    public TOperate(TOperate value) {
        this.id = value.id;
        this.operateName = value.operateName;
        this.categoryId = value.categoryId;
        this.isDelete = value.isDelete;
    }

    public TOperate(
        Integer id,
        String  operateName,
        Integer categoryId,
        Byte    isDelete
    ) {
        this.id = id;
        this.operateName = operateName;
        this.categoryId = categoryId;
        this.isDelete = isDelete;
    }

    public Integer getId() {
        return this.id;
    }

    public TOperate setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    @Size(max = 255)
    public String getOperateName() {
        return this.operateName;
    }

    public TOperate setOperateName(String operateName) {
        this.operateName = operateName;
        return this;
    }

    @NotNull
    public Integer getCategoryId() {
        return this.categoryId;
    }

    public TOperate setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
        return this;
    }

    public Byte getIsDelete() {
        return this.isDelete;
    }

    public TOperate setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TOperate other = (TOperate) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (operateName == null) {
            if (other.operateName != null)
                return false;
        }
        else if (!operateName.equals(other.operateName))
            return false;
        if (categoryId == null) {
            if (other.categoryId != null)
                return false;
        }
        else if (!categoryId.equals(other.categoryId))
            return false;
        if (isDelete == null) {
            if (other.isDelete != null)
                return false;
        }
        else if (!isDelete.equals(other.isDelete))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.operateName == null) ? 0 : this.operateName.hashCode());
        result = prime * result + ((this.categoryId == null) ? 0 : this.categoryId.hashCode());
        result = prime * result + ((this.isDelete == null) ? 0 : this.isDelete.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TOperate (");

        sb.append(id);
        sb.append(", ").append(operateName);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(isDelete);

        sb.append(")");
        return sb.toString();
    }
}
