/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * 所有中奖用户名单
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPrizeUserAll implements Serializable {

    private static final long serialVersionUID = -1150283052;

    private Integer       id;
    private Integer       userId;
    private String        nikename;
    private String        avatarFile;
    private Byte          type;
    private Integer       shareTimes;
    private LocalDate     prizeDate;
    private LocalDateTime postTime;

    public TPrizeUserAll() {}

    public TPrizeUserAll(TPrizeUserAll value) {
        this.id = value.id;
        this.userId = value.userId;
        this.nikename = value.nikename;
        this.avatarFile = value.avatarFile;
        this.type = value.type;
        this.shareTimes = value.shareTimes;
        this.prizeDate = value.prizeDate;
        this.postTime = value.postTime;
    }

    public TPrizeUserAll(
        Integer       id,
        Integer       userId,
        String        nikename,
        String        avatarFile,
        Byte          type,
        Integer       shareTimes,
        LocalDate     prizeDate,
        LocalDateTime postTime
    ) {
        this.id = id;
        this.userId = userId;
        this.nikename = nikename;
        this.avatarFile = avatarFile;
        this.type = type;
        this.shareTimes = shareTimes;
        this.prizeDate = prizeDate;
        this.postTime = postTime;
    }

    public Integer getId() {
        return this.id;
    }

    public TPrizeUserAll setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    public Integer getUserId() {
        return this.userId;
    }

    public TPrizeUserAll setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    @NotNull
    @Size(max = 32)
    public String getNikename() {
        return this.nikename;
    }

    public TPrizeUserAll setNikename(String nikename) {
        this.nikename = nikename;
        return this;
    }

    @NotNull
    @Size(max = 300)
    public String getAvatarFile() {
        return this.avatarFile;
    }

    public TPrizeUserAll setAvatarFile(String avatarFile) {
        this.avatarFile = avatarFile;
        return this;
    }

    @NotNull
    public Byte getType() {
        return this.type;
    }

    public TPrizeUserAll setType(Byte type) {
        this.type = type;
        return this;
    }

    public Integer getShareTimes() {
        return this.shareTimes;
    }

    public TPrizeUserAll setShareTimes(Integer shareTimes) {
        this.shareTimes = shareTimes;
        return this;
    }

    @NotNull
    public LocalDate getPrizeDate() {
        return this.prizeDate;
    }

    public TPrizeUserAll setPrizeDate(LocalDate prizeDate) {
        this.prizeDate = prizeDate;
        return this;
    }

    public LocalDateTime getPostTime() {
        return this.postTime;
    }

    public TPrizeUserAll setPostTime(LocalDateTime postTime) {
        this.postTime = postTime;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TPrizeUserAll other = (TPrizeUserAll) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (nikename == null) {
            if (other.nikename != null)
                return false;
        }
        else if (!nikename.equals(other.nikename))
            return false;
        if (avatarFile == null) {
            if (other.avatarFile != null)
                return false;
        }
        else if (!avatarFile.equals(other.avatarFile))
            return false;
        if (type == null) {
            if (other.type != null)
                return false;
        }
        else if (!type.equals(other.type))
            return false;
        if (shareTimes == null) {
            if (other.shareTimes != null)
                return false;
        }
        else if (!shareTimes.equals(other.shareTimes))
            return false;
        if (prizeDate == null) {
            if (other.prizeDate != null)
                return false;
        }
        else if (!prizeDate.equals(other.prizeDate))
            return false;
        if (postTime == null) {
            if (other.postTime != null)
                return false;
        }
        else if (!postTime.equals(other.postTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.nikename == null) ? 0 : this.nikename.hashCode());
        result = prime * result + ((this.avatarFile == null) ? 0 : this.avatarFile.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.shareTimes == null) ? 0 : this.shareTimes.hashCode());
        result = prime * result + ((this.prizeDate == null) ? 0 : this.prizeDate.hashCode());
        result = prime * result + ((this.postTime == null) ? 0 : this.postTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TPrizeUserAll (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(nikename);
        sb.append(", ").append(avatarFile);
        sb.append(", ").append(type);
        sb.append(", ").append(shareTimes);
        sb.append(", ").append(prizeDate);
        sb.append(", ").append(postTime);

        sb.append(")");
        return sb.toString();
    }
}
