/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TProject implements Serializable {

    private static final long serialVersionUID = 676189628;

    private Integer       id;
    private String        projectName;
    private String        link;
    private Integer       parentId;
    private Integer       level;
    private LocalDateTime createTime;

    public TProject() {}

    public TProject(TProject value) {
        this.id = value.id;
        this.projectName = value.projectName;
        this.link = value.link;
        this.parentId = value.parentId;
        this.level = value.level;
        this.createTime = value.createTime;
    }

    public TProject(
        Integer       id,
        String        projectName,
        String        link,
        Integer       parentId,
        Integer       level,
        LocalDateTime createTime
    ) {
        this.id = id;
        this.projectName = projectName;
        this.link = link;
        this.parentId = parentId;
        this.level = level;
        this.createTime = createTime;
    }

    public Integer getId() {
        return this.id;
    }

    public TProject setId(Integer id) {
        this.id = id;
        return this;
    }

    @Size(max = 255)
    public String getProjectName() {
        return this.projectName;
    }

    public TProject setProjectName(String projectName) {
        this.projectName = projectName;
        return this;
    }

    @Size(max = 255)
    public String getLink() {
        return this.link;
    }

    public TProject setLink(String link) {
        this.link = link;
        return this;
    }

    public Integer getParentId() {
        return this.parentId;
    }

    public TProject setParentId(Integer parentId) {
        this.parentId = parentId;
        return this;
    }

    public Integer getLevel() {
        return this.level;
    }

    public TProject setLevel(Integer level) {
        this.level = level;
        return this;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public TProject setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TProject other = (TProject) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (projectName == null) {
            if (other.projectName != null)
                return false;
        }
        else if (!projectName.equals(other.projectName))
            return false;
        if (link == null) {
            if (other.link != null)
                return false;
        }
        else if (!link.equals(other.link))
            return false;
        if (parentId == null) {
            if (other.parentId != null)
                return false;
        }
        else if (!parentId.equals(other.parentId))
            return false;
        if (level == null) {
            if (other.level != null)
                return false;
        }
        else if (!level.equals(other.level))
            return false;
        if (createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!createTime.equals(other.createTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.projectName == null) ? 0 : this.projectName.hashCode());
        result = prime * result + ((this.link == null) ? 0 : this.link.hashCode());
        result = prime * result + ((this.parentId == null) ? 0 : this.parentId.hashCode());
        result = prime * result + ((this.level == null) ? 0 : this.level.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TProject (");

        sb.append(id);
        sb.append(", ").append(projectName);
        sb.append(", ").append(link);
        sb.append(", ").append(parentId);
        sb.append(", ").append(level);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
