/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * 房间复查记录表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRecheckRecord implements Serializable {

    private static final long serialVersionUID = -1647251249;

    private Integer       id;
    private Integer       groupLeaderId;
    private Integer       accountId;
    private Integer       roomId;
    private Integer       roomMemberId;
    private LocalDateTime postTime;
    private Byte          status;
    private Integer       liveResolveId;

    public TRecheckRecord() {}

    public TRecheckRecord(TRecheckRecord value) {
        this.id = value.id;
        this.groupLeaderId = value.groupLeaderId;
        this.accountId = value.accountId;
        this.roomId = value.roomId;
        this.roomMemberId = value.roomMemberId;
        this.postTime = value.postTime;
        this.status = value.status;
        this.liveResolveId = value.liveResolveId;
    }

    public TRecheckRecord(
        Integer       id,
        Integer       groupLeaderId,
        Integer       accountId,
        Integer       roomId,
        Integer       roomMemberId,
        LocalDateTime postTime,
        Byte          status,
        Integer       liveResolveId
    ) {
        this.id = id;
        this.groupLeaderId = groupLeaderId;
        this.accountId = accountId;
        this.roomId = roomId;
        this.roomMemberId = roomMemberId;
        this.postTime = postTime;
        this.status = status;
        this.liveResolveId = liveResolveId;
    }

    public Integer getId() {
        return this.id;
    }

    public TRecheckRecord setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    public Integer getGroupLeaderId() {
        return this.groupLeaderId;
    }

    public TRecheckRecord setGroupLeaderId(Integer groupLeaderId) {
        this.groupLeaderId = groupLeaderId;
        return this;
    }

    @NotNull
    public Integer getAccountId() {
        return this.accountId;
    }

    public TRecheckRecord setAccountId(Integer accountId) {
        this.accountId = accountId;
        return this;
    }

    @NotNull
    public Integer getRoomId() {
        return this.roomId;
    }

    public TRecheckRecord setRoomId(Integer roomId) {
        this.roomId = roomId;
        return this;
    }

    @NotNull
    public Integer getRoomMemberId() {
        return this.roomMemberId;
    }

    public TRecheckRecord setRoomMemberId(Integer roomMemberId) {
        this.roomMemberId = roomMemberId;
        return this;
    }

    public LocalDateTime getPostTime() {
        return this.postTime;
    }

    public TRecheckRecord setPostTime(LocalDateTime postTime) {
        this.postTime = postTime;
        return this;
    }

    public Byte getStatus() {
        return this.status;
    }

    public TRecheckRecord setStatus(Byte status) {
        this.status = status;
        return this;
    }

    public Integer getLiveResolveId() {
        return this.liveResolveId;
    }

    public TRecheckRecord setLiveResolveId(Integer liveResolveId) {
        this.liveResolveId = liveResolveId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TRecheckRecord other = (TRecheckRecord) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (groupLeaderId == null) {
            if (other.groupLeaderId != null)
                return false;
        }
        else if (!groupLeaderId.equals(other.groupLeaderId))
            return false;
        if (accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!accountId.equals(other.accountId))
            return false;
        if (roomId == null) {
            if (other.roomId != null)
                return false;
        }
        else if (!roomId.equals(other.roomId))
            return false;
        if (roomMemberId == null) {
            if (other.roomMemberId != null)
                return false;
        }
        else if (!roomMemberId.equals(other.roomMemberId))
            return false;
        if (postTime == null) {
            if (other.postTime != null)
                return false;
        }
        else if (!postTime.equals(other.postTime))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (liveResolveId == null) {
            if (other.liveResolveId != null)
                return false;
        }
        else if (!liveResolveId.equals(other.liveResolveId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.groupLeaderId == null) ? 0 : this.groupLeaderId.hashCode());
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        result = prime * result + ((this.roomId == null) ? 0 : this.roomId.hashCode());
        result = prime * result + ((this.roomMemberId == null) ? 0 : this.roomMemberId.hashCode());
        result = prime * result + ((this.postTime == null) ? 0 : this.postTime.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.liveResolveId == null) ? 0 : this.liveResolveId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRecheckRecord (");

        sb.append(id);
        sb.append(", ").append(groupLeaderId);
        sb.append(", ").append(accountId);
        sb.append(", ").append(roomId);
        sb.append(", ").append(roomMemberId);
        sb.append(", ").append(postTime);
        sb.append(", ").append(status);
        sb.append(", ").append(liveResolveId);

        sb.append(")");
        return sb.toString();
    }
}
