/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TResource implements Serializable {

    private static final long serialVersionUID = -521122543;

    private Integer id;
    private Integer operateId;
    private String  url;

    public TResource() {}

    public TResource(TResource value) {
        this.id = value.id;
        this.operateId = value.operateId;
        this.url = value.url;
    }

    public TResource(
        Integer id,
        Integer operateId,
        String  url
    ) {
        this.id = id;
        this.operateId = operateId;
        this.url = url;
    }

    public Integer getId() {
        return this.id;
    }

    public TResource setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getOperateId() {
        return this.operateId;
    }

    public TResource setOperateId(Integer operateId) {
        this.operateId = operateId;
        return this;
    }

    @Size(max = 255)
    public String getUrl() {
        return this.url;
    }

    public TResource setUrl(String url) {
        this.url = url;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TResource other = (TResource) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (operateId == null) {
            if (other.operateId != null)
                return false;
        }
        else if (!operateId.equals(other.operateId))
            return false;
        if (url == null) {
            if (other.url != null)
                return false;
        }
        else if (!url.equals(other.url))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.operateId == null) ? 0 : this.operateId.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TResource (");

        sb.append(id);
        sb.append(", ").append(operateId);
        sb.append(", ").append(url);

        sb.append(")");
        return sb.toString();
    }
}
