/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRoleOperate implements Serializable {

    private static final long serialVersionUID = -1717820539;

    private Integer id;
    private Integer roleId;
    private Integer operateId;

    public TRoleOperate() {}

    public TRoleOperate(TRoleOperate value) {
        this.id = value.id;
        this.roleId = value.roleId;
        this.operateId = value.operateId;
    }

    public TRoleOperate(
        Integer id,
        Integer roleId,
        Integer operateId
    ) {
        this.id = id;
        this.roleId = roleId;
        this.operateId = operateId;
    }

    public Integer getId() {
        return this.id;
    }

    public TRoleOperate setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    public Integer getRoleId() {
        return this.roleId;
    }

    public TRoleOperate setRoleId(Integer roleId) {
        this.roleId = roleId;
        return this;
    }

    @NotNull
    public Integer getOperateId() {
        return this.operateId;
    }

    public TRoleOperate setOperateId(Integer operateId) {
        this.operateId = operateId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TRoleOperate other = (TRoleOperate) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (roleId == null) {
            if (other.roleId != null)
                return false;
        }
        else if (!roleId.equals(other.roleId))
            return false;
        if (operateId == null) {
            if (other.operateId != null)
                return false;
        }
        else if (!operateId.equals(other.operateId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.roleId == null) ? 0 : this.roleId.hashCode());
        result = prime * result + ((this.operateId == null) ? 0 : this.operateId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRoleOperate (");

        sb.append(id);
        sb.append(", ").append(roleId);
        sb.append(", ").append(operateId);

        sb.append(")");
        return sb.toString();
    }
}
