/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRoleProject implements Serializable {

    private static final long serialVersionUID = -125569342;

    private Integer id;
    private Integer roleId;
    private Integer projectId;

    public TRoleProject() {}

    public TRoleProject(TRoleProject value) {
        this.id = value.id;
        this.roleId = value.roleId;
        this.projectId = value.projectId;
    }

    public TRoleProject(
        Integer id,
        Integer roleId,
        Integer projectId
    ) {
        this.id = id;
        this.roleId = roleId;
        this.projectId = projectId;
    }

    public Integer getId() {
        return this.id;
    }

    public TRoleProject setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public TRoleProject setRoleId(Integer roleId) {
        this.roleId = roleId;
        return this;
    }

    public Integer getProjectId() {
        return this.projectId;
    }

    public TRoleProject setProjectId(Integer projectId) {
        this.projectId = projectId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TRoleProject other = (TRoleProject) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (roleId == null) {
            if (other.roleId != null)
                return false;
        }
        else if (!roleId.equals(other.roleId))
            return false;
        if (projectId == null) {
            if (other.projectId != null)
                return false;
        }
        else if (!projectId.equals(other.projectId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.roleId == null) ? 0 : this.roleId.hashCode());
        result = prime * result + ((this.projectId == null) ? 0 : this.projectId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRoleProject (");

        sb.append(id);
        sb.append(", ").append(roleId);
        sb.append(", ").append(projectId);

        sb.append(")");
        return sb.toString();
    }
}
