/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRole implements Serializable {

    private static final long serialVersionUID = 351401164;

    private Integer       id;
    private String        roleName;
    private LocalDateTime createTime;

    public TRole() {}

    public TRole(TRole value) {
        this.id = value.id;
        this.roleName = value.roleName;
        this.createTime = value.createTime;
    }

    public TRole(
        Integer       id,
        String        roleName,
        LocalDateTime createTime
    ) {
        this.id = id;
        this.roleName = roleName;
        this.createTime = createTime;
    }

    public Integer getId() {
        return this.id;
    }

    public TRole setId(Integer id) {
        this.id = id;
        return this;
    }

    @Size(max = 255)
    public String getRoleName() {
        return this.roleName;
    }

    public TRole setRoleName(String roleName) {
        this.roleName = roleName;
        return this;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public TRole setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TRole other = (TRole) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (roleName == null) {
            if (other.roleName != null)
                return false;
        }
        else if (!roleName.equals(other.roleName))
            return false;
        if (createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!createTime.equals(other.createTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.roleName == null) ? 0 : this.roleName.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRole (");

        sb.append(id);
        sb.append(", ").append(roleName);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
