/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRoomMemberCheck implements Serializable {

    private static final long serialVersionUID = 619296966;

    private Integer       id;
    private Integer       roomId;
    private Integer       userId;
    private LocalDateTime postTime;
    private Integer       accountId;

    public TRoomMemberCheck() {}

    public TRoomMemberCheck(TRoomMemberCheck value) {
        this.id = value.id;
        this.roomId = value.roomId;
        this.userId = value.userId;
        this.postTime = value.postTime;
        this.accountId = value.accountId;
    }

    public TRoomMemberCheck(
        Integer       id,
        Integer       roomId,
        Integer       userId,
        LocalDateTime postTime,
        Integer       accountId
    ) {
        this.id = id;
        this.roomId = roomId;
        this.userId = userId;
        this.postTime = postTime;
        this.accountId = accountId;
    }

    public Integer getId() {
        return this.id;
    }

    public TRoomMemberCheck setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    public Integer getRoomId() {
        return this.roomId;
    }

    public TRoomMemberCheck setRoomId(Integer roomId) {
        this.roomId = roomId;
        return this;
    }

    @NotNull
    public Integer getUserId() {
        return this.userId;
    }

    public TRoomMemberCheck setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    public LocalDateTime getPostTime() {
        return this.postTime;
    }

    public TRoomMemberCheck setPostTime(LocalDateTime postTime) {
        this.postTime = postTime;
        return this;
    }

    public Integer getAccountId() {
        return this.accountId;
    }

    public TRoomMemberCheck setAccountId(Integer accountId) {
        this.accountId = accountId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TRoomMemberCheck other = (TRoomMemberCheck) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (roomId == null) {
            if (other.roomId != null)
                return false;
        }
        else if (!roomId.equals(other.roomId))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (postTime == null) {
            if (other.postTime != null)
                return false;
        }
        else if (!postTime.equals(other.postTime))
            return false;
        if (accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!accountId.equals(other.accountId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.roomId == null) ? 0 : this.roomId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.postTime == null) ? 0 : this.postTime.hashCode());
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRoomMemberCheck (");

        sb.append(id);
        sb.append(", ").append(roomId);
        sb.append(", ").append(userId);
        sb.append(", ").append(postTime);
        sb.append(", ").append(accountId);

        sb.append(")");
        return sb.toString();
    }
}
