/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TShareRecord implements Serializable {

    private static final long serialVersionUID = -1097794132;

    private Integer       id;
    private Integer       userID;
    private String        url;
    private LocalDateTime postTime;

    public TShareRecord() {}

    public TShareRecord(TShareRecord value) {
        this.id = value.id;
        this.userID = value.userID;
        this.url = value.url;
        this.postTime = value.postTime;
    }

    public TShareRecord(
        Integer       id,
        Integer       userID,
        String        url,
        LocalDateTime postTime
    ) {
        this.id = id;
        this.userID = userID;
        this.url = url;
        this.postTime = postTime;
    }

    public Integer getId() {
        return this.id;
    }

    public TShareRecord setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    public Integer getUserID() {
        return this.userID;
    }

    public TShareRecord setUserID(Integer userID) {
        this.userID = userID;
        return this;
    }

    @NotNull
    @Size(max = 255)
    public String getUrl() {
        return this.url;
    }

    public TShareRecord setUrl(String url) {
        this.url = url;
        return this;
    }

    public LocalDateTime getPostTime() {
        return this.postTime;
    }

    public TShareRecord setPostTime(LocalDateTime postTime) {
        this.postTime = postTime;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TShareRecord other = (TShareRecord) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (userID == null) {
            if (other.userID != null)
                return false;
        }
        else if (!userID.equals(other.userID))
            return false;
        if (url == null) {
            if (other.url != null)
                return false;
        }
        else if (!url.equals(other.url))
            return false;
        if (postTime == null) {
            if (other.postTime != null)
                return false;
        }
        else if (!postTime.equals(other.postTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userID == null) ? 0 : this.userID.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        result = prime * result + ((this.postTime == null) ? 0 : this.postTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TShareRecord (");

        sb.append(id);
        sb.append(", ").append(userID);
        sb.append(", ").append(url);
        sb.append(", ").append(postTime);

        sb.append(")");
        return sb.toString();
    }
}
