/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserMessage implements Serializable {

    private static final long serialVersionUID = -790025106;

    private Integer       id;
    private Integer       userID;
    private String        content;
    private LocalDateTime postTime;

    public TUserMessage() {}

    public TUserMessage(TUserMessage value) {
        this.id = value.id;
        this.userID = value.userID;
        this.content = value.content;
        this.postTime = value.postTime;
    }

    public TUserMessage(
        Integer       id,
        Integer       userID,
        String        content,
        LocalDateTime postTime
    ) {
        this.id = id;
        this.userID = userID;
        this.content = content;
        this.postTime = postTime;
    }

    public Integer getId() {
        return this.id;
    }

    public TUserMessage setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    public Integer getUserID() {
        return this.userID;
    }

    public TUserMessage setUserID(Integer userID) {
        this.userID = userID;
        return this;
    }

    @Size(max = 255)
    public String getContent() {
        return this.content;
    }

    public TUserMessage setContent(String content) {
        this.content = content;
        return this;
    }

    public LocalDateTime getPostTime() {
        return this.postTime;
    }

    public TUserMessage setPostTime(LocalDateTime postTime) {
        this.postTime = postTime;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TUserMessage other = (TUserMessage) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (userID == null) {
            if (other.userID != null)
                return false;
        }
        else if (!userID.equals(other.userID))
            return false;
        if (content == null) {
            if (other.content != null)
                return false;
        }
        else if (!content.equals(other.content))
            return false;
        if (postTime == null) {
            if (other.postTime != null)
                return false;
        }
        else if (!postTime.equals(other.postTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userID == null) ? 0 : this.userID.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        result = prime * result + ((this.postTime == null) ? 0 : this.postTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUserMessage (");

        sb.append(id);
        sb.append(", ").append(userID);
        sb.append(", ").append(content);
        sb.append(", ").append(postTime);

        sb.append(")");
        return sb.toString();
    }
}
