/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.records;


import com.example.mvc.table.tables.TAccount;

import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccountRecord extends UpdatableRecordImpl<TAccountRecord> implements Record9<Integer, String, String, LocalDateTime, LocalDateTime, Byte, Integer, String, Byte> {

    private static final long serialVersionUID = -1073907279;

    /**
     * Setter for <code>kelu.t_account.id</code>.
     */
    public TAccountRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_account.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kelu.t_account.username</code>.
     */
    public TAccountRecord setUsername(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_account.username</code>.
     */
    @Size(max = 255)
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kelu.t_account.password</code>. 1234
     */
    public TAccountRecord setPassword(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_account.password</code>. 1234
     */
    @Size(max = 255)
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kelu.t_account.create_time</code>.
     */
    public TAccountRecord setCreateTime(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_account.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>kelu.t_account.last_time</code>.
     */
    public TAccountRecord setLastTime(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_account.last_time</code>.
     */
    public LocalDateTime getLastTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>kelu.t_account.is_admin</code>.
     */
    public TAccountRecord setIsAdmin(Byte value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_account.is_admin</code>.
     */
    public Byte getIsAdmin() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>kelu.t_account.department_id</code>.
     */
    public TAccountRecord setDepartmentId(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_account.department_id</code>.
     */
    public Integer getDepartmentId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>kelu.t_account.nickname</code>.
     */
    public TAccountRecord setNickname(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_account.nickname</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getNickname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>kelu.t_account.is_disabled</code>. 0为没封禁 1为封禁
     */
    public TAccountRecord setIsDisabled(Byte value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_account.is_disabled</code>. 0为没封禁 1为封禁
     */
    public Byte getIsDisabled() {
        return (Byte) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, LocalDateTime, LocalDateTime, Byte, Integer, String, Byte> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, LocalDateTime, LocalDateTime, Byte, Integer, String, Byte> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TAccount.t_account.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TAccount.t_account.username;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TAccount.t_account.password;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return TAccount.t_account.create_time;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return TAccount.t_account.last_time;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return TAccount.t_account.is_admin;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TAccount.t_account.department_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TAccount.t_account.nickname;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return TAccount.t_account.is_disabled;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component5() {
        return getLastTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getIsAdmin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getIsDisabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getLastTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getIsAdmin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getIsDisabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountRecord value2(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountRecord value3(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountRecord value4(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountRecord value5(LocalDateTime value) {
        setLastTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountRecord value6(Byte value) {
        setIsAdmin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountRecord value7(Integer value) {
        setDepartmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountRecord value8(String value) {
        setNickname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountRecord value9(Byte value) {
        setIsDisabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountRecord values(Integer value1, String value2, String value3, LocalDateTime value4, LocalDateTime value5, Byte value6, Integer value7, String value8, Byte value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TAccountRecord
     */
    public TAccountRecord() {
        super(TAccount.t_account);
    }

    /**
     * Create a detached, initialised TAccountRecord
     */
    public TAccountRecord(Integer id, String username, String password, LocalDateTime createTime, LocalDateTime lastTime, Byte isAdmin, Integer departmentId, String nickname, Byte isDisabled) {
        super(TAccount.t_account);

        set(0, id);
        set(1, username);
        set(2, password);
        set(3, createTime);
        set(4, lastTime);
        set(5, isAdmin);
        set(6, departmentId);
        set(7, nickname);
        set(8, isDisabled);
    }
}
