/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.records;


import com.example.mvc.table.tables.TActivityText;

import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 文案表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TActivityTextRecord extends UpdatableRecordImpl<TActivityTextRecord> implements Record8<Integer, String, String, Integer, String, String, Byte, LocalDateTime> {

    private static final long serialVersionUID = -1506231385;

    /**
     * Setter for <code>kelu.t_activity_text.id</code>.
     */
    public TActivityTextRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_activity_text.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kelu.t_activity_text.title</code>. 标题
     */
    public TActivityTextRecord setTitle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_activity_text.title</code>. 标题
     */
    @Size(max = 100)
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kelu.t_activity_text.content</code>. 内容
     */
    public TActivityTextRecord setContent(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_activity_text.content</code>. 内容
     */
    @Size(max = 200)
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kelu.t_activity_text.feedId</code>. 日志id
     */
    public TActivityTextRecord setFeedId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_activity_text.feedId</code>. 日志id
     */
    public Integer getFeedId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>kelu.t_activity_text.video_file</code>. 视频文件名
     */
    public TActivityTextRecord setVideoFile(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_activity_text.video_file</code>. 视频文件名
     */
    @Size(max = 300)
    public String getVideoFile() {
        return (String) get(4);
    }

    /**
     * Setter for <code>kelu.t_activity_text.cover_file</code>. 视频封面文件名
     */
    public TActivityTextRecord setCoverFile(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_activity_text.cover_file</code>. 视频封面文件名
     */
    @Size(max = 300)
    public String getCoverFile() {
        return (String) get(5);
    }

    /**
     * Setter for <code>kelu.t_activity_text.is_use</code>. 是否正在使用
     */
    public TActivityTextRecord setIsUse(Byte value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_activity_text.is_use</code>. 是否正在使用
     */
    public Byte getIsUse() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>kelu.t_activity_text.post_time</code>.
     */
    public TActivityTextRecord setPostTime(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_activity_text.post_time</code>.
     */
    public LocalDateTime getPostTime() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Integer, String, String, Byte, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Integer, String, String, Byte, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TActivityText.t_activity_text.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TActivityText.t_activity_text.title;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TActivityText.t_activity_text.content;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TActivityText.t_activity_text.feedId;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TActivityText.t_activity_text.video_file;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TActivityText.t_activity_text.cover_file;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return TActivityText.t_activity_text.is_use;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return TActivityText.t_activity_text.post_time;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getFeedId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getVideoFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCoverFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getIsUse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getPostTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getFeedId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getVideoFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCoverFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getIsUse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getPostTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityTextRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityTextRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityTextRecord value3(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityTextRecord value4(Integer value) {
        setFeedId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityTextRecord value5(String value) {
        setVideoFile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityTextRecord value6(String value) {
        setCoverFile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityTextRecord value7(Byte value) {
        setIsUse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityTextRecord value8(LocalDateTime value) {
        setPostTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityTextRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, Byte value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TActivityTextRecord
     */
    public TActivityTextRecord() {
        super(TActivityText.t_activity_text);
    }

    /**
     * Create a detached, initialised TActivityTextRecord
     */
    public TActivityTextRecord(Integer id, String title, String content, Integer feedId, String videoFile, String coverFile, Byte isUse, LocalDateTime postTime) {
        super(TActivityText.t_activity_text);

        set(0, id);
        set(1, title);
        set(2, content);
        set(3, feedId);
        set(4, videoFile);
        set(5, coverFile);
        set(6, isUse);
        set(7, postTime);
    }
}
