/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.records;


import com.example.mvc.table.tables.TFeedLabelRecord;

import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TFeedLabelRecordRecord extends UpdatableRecordImpl<TFeedLabelRecordRecord> implements Record5<Integer, Integer, Integer, LocalDateTime, Byte> {

    private static final long serialVersionUID = -2043318258;

    /**
     * Setter for <code>kelu.t_feed_label_record.id</code>.
     */
    public TFeedLabelRecordRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_feed_label_record.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kelu.t_feed_label_record.feed_id</code>.
     */
    public TFeedLabelRecordRecord setFeedId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_feed_label_record.feed_id</code>.
     */
    @NotNull
    public Integer getFeedId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kelu.t_feed_label_record.account_id</code>.
     */
    public TFeedLabelRecordRecord setAccountId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_feed_label_record.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>kelu.t_feed_label_record.post_time</code>.
     */
    public TFeedLabelRecordRecord setPostTime(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_feed_label_record.post_time</code>.
     */
    public LocalDateTime getPostTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>kelu.t_feed_label_record.status</code>. 0 代表未审核  1代表已审核
     */
    public TFeedLabelRecordRecord setStatus(Byte value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_feed_label_record.status</code>. 0 代表未审核  1代表已审核
     */
    public Byte getStatus() {
        return (Byte) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, LocalDateTime, Byte> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, LocalDateTime, Byte> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TFeedLabelRecord.t_feed_label_record.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TFeedLabelRecord.t_feed_label_record.feed_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TFeedLabelRecord.t_feed_label_record.account_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return TFeedLabelRecord.t_feed_label_record.post_time;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return TFeedLabelRecord.t_feed_label_record.status;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getFeedId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getPostTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getFeedId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getPostTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFeedLabelRecordRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFeedLabelRecordRecord value2(Integer value) {
        setFeedId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFeedLabelRecordRecord value3(Integer value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFeedLabelRecordRecord value4(LocalDateTime value) {
        setPostTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFeedLabelRecordRecord value5(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFeedLabelRecordRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4, Byte value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TFeedLabelRecordRecord
     */
    public TFeedLabelRecordRecord() {
        super(TFeedLabelRecord.t_feed_label_record);
    }

    /**
     * Create a detached, initialised TFeedLabelRecordRecord
     */
    public TFeedLabelRecordRecord(Integer id, Integer feedId, Integer accountId, LocalDateTime postTime, Byte status) {
        super(TFeedLabelRecord.t_feed_label_record);

        set(0, id);
        set(1, feedId);
        set(2, accountId);
        set(3, postTime);
        set(4, status);
    }
}
