/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.records;


import com.example.mvc.table.tables.TFlag;

import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TFlagRecord extends UpdatableRecordImpl<TFlagRecord> implements Record8<Integer, Integer, String, String, Integer, Integer, String, LocalDateTime> {

    private static final long serialVersionUID = -344219663;

    /**
     * Setter for <code>kelu.t_flag.id</code>.
     */
    public TFlagRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_flag.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kelu.t_flag.user_Id</code>. 用户id
     */
    public TFlagRecord setUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_flag.user_Id</code>. 用户id
     */
    @NotNull
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kelu.t_flag.nickname</code>. 用户昵称
     */
    public TFlagRecord setNickname(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_flag.nickname</code>. 用户昵称
     */
    @NotNull
    @Size(max = 100)
    public String getNickname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kelu.t_flag.flag</code>. 用户flag
     */
    public TFlagRecord setFlag(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_flag.flag</code>. 用户flag
     */
    @NotNull
    @Size(max = 20)
    public String getFlag() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kelu.t_flag.approve</code>. 赞成
     */
    public TFlagRecord setApprove(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_flag.approve</code>. 赞成
     */
    public Integer getApprove() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>kelu.t_flag.opposition</code>. 反对
     */
    public TFlagRecord setOpposition(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_flag.opposition</code>. 反对
     */
    public Integer getOpposition() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>kelu.t_flag.pic</code>. flag图文件名
     */
    public TFlagRecord setPic(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_flag.pic</code>. flag图文件名
     */
    @NotNull
    @Size(max = 300)
    public String getPic() {
        return (String) get(6);
    }

    /**
     * Setter for <code>kelu.t_flag.postTime</code>.
     */
    public TFlagRecord setPostTime(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_flag.postTime</code>.
     */
    public LocalDateTime getPostTime() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, String, String, Integer, Integer, String, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, String, String, Integer, Integer, String, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TFlag.t_flag.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TFlag.t_flag.user_Id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TFlag.t_flag.nickname;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TFlag.t_flag.flag;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TFlag.t_flag.approve;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TFlag.t_flag.opposition;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TFlag.t_flag.pic;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return TFlag.t_flag.postTime;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getApprove();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getOpposition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getPostTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getApprove();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getOpposition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getPostTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFlagRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFlagRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFlagRecord value3(String value) {
        setNickname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFlagRecord value4(String value) {
        setFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFlagRecord value5(Integer value) {
        setApprove(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFlagRecord value6(Integer value) {
        setOpposition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFlagRecord value7(String value) {
        setPic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFlagRecord value8(LocalDateTime value) {
        setPostTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFlagRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5, Integer value6, String value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TFlagRecord
     */
    public TFlagRecord() {
        super(TFlag.t_flag);
    }

    /**
     * Create a detached, initialised TFlagRecord
     */
    public TFlagRecord(Integer id, Integer userId, String nickname, String flag, Integer approve, Integer opposition, String pic, LocalDateTime postTime) {
        super(TFlag.t_flag);

        set(0, id);
        set(1, userId);
        set(2, nickname);
        set(3, flag);
        set(4, approve);
        set(5, opposition);
        set(6, pic);
        set(7, postTime);
    }
}
