/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.records;


import com.example.mvc.table.tables.TOperate;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOperateRecord extends UpdatableRecordImpl<TOperateRecord> implements Record4<Integer, String, Integer, Byte> {

    private static final long serialVersionUID = 1549804320;

    /**
     * Setter for <code>kelu.t_operate.id</code>.
     */
    public TOperateRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_operate.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kelu.t_operate.operate_name</code>.
     */
    public TOperateRecord setOperateName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_operate.operate_name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getOperateName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kelu.t_operate.category_id</code>.
     */
    public TOperateRecord setCategoryId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_operate.category_id</code>.
     */
    @NotNull
    public Integer getCategoryId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>kelu.t_operate.is_delete</code>.
     */
    public TOperateRecord setIsDelete(Byte value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_operate.is_delete</code>.
     */
    public Byte getIsDelete() {
        return (Byte) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Byte> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Byte> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TOperate.t_operate.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TOperate.t_operate.operate_name;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TOperate.t_operate.category_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return TOperate.t_operate.is_delete;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getOperateName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOperateName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOperateRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOperateRecord value2(String value) {
        setOperateName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOperateRecord value3(Integer value) {
        setCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOperateRecord value4(Byte value) {
        setIsDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOperateRecord values(Integer value1, String value2, Integer value3, Byte value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TOperateRecord
     */
    public TOperateRecord() {
        super(TOperate.t_operate);
    }

    /**
     * Create a detached, initialised TOperateRecord
     */
    public TOperateRecord(Integer id, String operateName, Integer categoryId, Byte isDelete) {
        super(TOperate.t_operate);

        set(0, id);
        set(1, operateName);
        set(2, categoryId);
        set(3, isDelete);
    }
}
