/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.records;


import com.example.mvc.table.tables.TPrizeFake;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 有奖征集视频假名单
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPrizeFakeRecord extends UpdatableRecordImpl<TPrizeFakeRecord> implements Record4<Integer, Integer, String, String> {

    private static final long serialVersionUID = 1014521726;

    /**
     * Setter for <code>kelu.t_prize_fake.id</code>.
     */
    public TPrizeFakeRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_prize_fake.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kelu.t_prize_fake.userId</code>. 用户id
     */
    public TPrizeFakeRecord setUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_prize_fake.userId</code>. 用户id
     */
    @NotNull
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kelu.t_prize_fake.nikename</code>. 昵称
     */
    public TPrizeFakeRecord setNikename(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_prize_fake.nikename</code>. 昵称
     */
    @NotNull
    @Size(max = 100)
    public String getNikename() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kelu.t_prize_fake.avatar_file</code>. 头像文件名
     */
    public TPrizeFakeRecord setAvatarFile(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_prize_fake.avatar_file</code>. 头像文件名
     */
    @NotNull
    @Size(max = 100)
    public String getAvatarFile() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TPrizeFake.t_prize_fake.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TPrizeFake.t_prize_fake.userId;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TPrizeFake.t_prize_fake.nikename;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TPrizeFake.t_prize_fake.avatar_file;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNikename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAvatarFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNikename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAvatarFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeFakeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeFakeRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeFakeRecord value3(String value) {
        setNikename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeFakeRecord value4(String value) {
        setAvatarFile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeFakeRecord values(Integer value1, Integer value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TPrizeFakeRecord
     */
    public TPrizeFakeRecord() {
        super(TPrizeFake.t_prize_fake);
    }

    /**
     * Create a detached, initialised TPrizeFakeRecord
     */
    public TPrizeFakeRecord(Integer id, Integer userId, String nikename, String avatarFile) {
        super(TPrizeFake.t_prize_fake);

        set(0, id);
        set(1, userId);
        set(2, nikename);
        set(3, avatarFile);
    }
}
