/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.records;


import com.example.mvc.table.tables.TPrizeUser;

import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 中奖用户
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPrizeUserRecord extends UpdatableRecordImpl<TPrizeUserRecord> implements Record8<Integer, Integer, String, String, Byte, Integer, LocalDate, LocalDateTime> {

    private static final long serialVersionUID = 822736940;

    /**
     * Setter for <code>kelu.t_prize_user.id</code>.
     */
    public TPrizeUserRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_prize_user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kelu.t_prize_user.userId</code>. 用户Id
     */
    public TPrizeUserRecord setUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_prize_user.userId</code>. 用户Id
     */
    @NotNull
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kelu.t_prize_user.nickname</code>. 昵称
     */
    public TPrizeUserRecord setNickname(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_prize_user.nickname</code>. 昵称
     */
    @NotNull
    @Size(max = 32)
    public String getNickname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kelu.t_prize_user.avatar_file</code>. 头像
     */
    public TPrizeUserRecord setAvatarFile(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_prize_user.avatar_file</code>. 头像
     */
    @NotNull
    @Size(max = 300)
    public String getAvatarFile() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kelu.t_prize_user.type</code>. 1.每天中奖 2.5天中奖
     */
    public TPrizeUserRecord setType(Byte value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_prize_user.type</code>. 1.每天中奖 2.5天中奖
     */
    @NotNull
    public Byte getType() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>kelu.t_prize_user.share_times</code>. 分享次数
     */
    public TPrizeUserRecord setShareTimes(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_prize_user.share_times</code>. 分享次数
     */
    public Integer getShareTimes() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>kelu.t_prize_user.prize_date</code>. 中奖日期
     */
    public TPrizeUserRecord setPrizeDate(LocalDate value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_prize_user.prize_date</code>. 中奖日期
     */
    @NotNull
    public LocalDate getPrizeDate() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>kelu.t_prize_user.post_time</code>.
     */
    public TPrizeUserRecord setPostTime(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_prize_user.post_time</code>.
     */
    public LocalDateTime getPostTime() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, String, String, Byte, Integer, LocalDate, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, String, String, Byte, Integer, LocalDate, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TPrizeUser.t_prize_user.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TPrizeUser.t_prize_user.userId;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TPrizeUser.t_prize_user.nickname;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TPrizeUser.t_prize_user.avatar_file;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return TPrizeUser.t_prize_user.type;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TPrizeUser.t_prize_user.share_times;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field7() {
        return TPrizeUser.t_prize_user.prize_date;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return TPrizeUser.t_prize_user.post_time;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAvatarFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getShareTimes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate component7() {
        return getPrizeDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getPostTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAvatarFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getShareTimes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value7() {
        return getPrizeDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getPostTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeUserRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeUserRecord value3(String value) {
        setNickname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeUserRecord value4(String value) {
        setAvatarFile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeUserRecord value5(Byte value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeUserRecord value6(Integer value) {
        setShareTimes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeUserRecord value7(LocalDate value) {
        setPrizeDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeUserRecord value8(LocalDateTime value) {
        setPostTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPrizeUserRecord values(Integer value1, Integer value2, String value3, String value4, Byte value5, Integer value6, LocalDate value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TPrizeUserRecord
     */
    public TPrizeUserRecord() {
        super(TPrizeUser.t_prize_user);
    }

    /**
     * Create a detached, initialised TPrizeUserRecord
     */
    public TPrizeUserRecord(Integer id, Integer userId, String nickname, String avatarFile, Byte type, Integer shareTimes, LocalDate prizeDate, LocalDateTime postTime) {
        super(TPrizeUser.t_prize_user);

        set(0, id);
        set(1, userId);
        set(2, nickname);
        set(3, avatarFile);
        set(4, type);
        set(5, shareTimes);
        set(6, prizeDate);
        set(7, postTime);
    }
}
