/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.records;


import com.example.mvc.table.tables.TProject;

import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TProjectRecord extends UpdatableRecordImpl<TProjectRecord> implements Record6<Integer, String, String, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = -687034597;

    /**
     * Setter for <code>kelu.t_project.id</code>.
     */
    public TProjectRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_project.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kelu.t_project.project_name</code>.
     */
    public TProjectRecord setProjectName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_project.project_name</code>.
     */
    @Size(max = 255)
    public String getProjectName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kelu.t_project.link</code>.
     */
    public TProjectRecord setLink(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_project.link</code>.
     */
    @Size(max = 255)
    public String getLink() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kelu.t_project.parent_id</code>.
     */
    public TProjectRecord setParentId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_project.parent_id</code>.
     */
    public Integer getParentId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>kelu.t_project.level</code>.
     */
    public TProjectRecord setLevel(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_project.level</code>.
     */
    public Integer getLevel() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>kelu.t_project.create_time</code>.
     */
    public TProjectRecord setCreateTime(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_project.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TProject.t_project.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TProject.t_project.project_name;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TProject.t_project.link;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TProject.t_project.parent_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TProject.t_project.level;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return TProject.t_project.create_time;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProjectName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProjectName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProjectRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProjectRecord value2(String value) {
        setProjectName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProjectRecord value3(String value) {
        setLink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProjectRecord value4(Integer value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProjectRecord value5(Integer value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProjectRecord value6(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProjectRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TProjectRecord
     */
    public TProjectRecord() {
        super(TProject.t_project);
    }

    /**
     * Create a detached, initialised TProjectRecord
     */
    public TProjectRecord(Integer id, String projectName, String link, Integer parentId, Integer level, LocalDateTime createTime) {
        super(TProject.t_project);

        set(0, id);
        set(1, projectName);
        set(2, link);
        set(3, parentId);
        set(4, level);
        set(5, createTime);
    }
}
