/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.records;


import com.example.mvc.table.tables.TRoleOperate;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRoleOperateRecord extends UpdatableRecordImpl<TRoleOperateRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -50280127;

    /**
     * Setter for <code>kelu.t_role_operate.id</code>.
     */
    public TRoleOperateRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_role_operate.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kelu.t_role_operate.role_id</code>.
     */
    public TRoleOperateRecord setRoleId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_role_operate.role_id</code>.
     */
    @NotNull
    public Integer getRoleId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kelu.t_role_operate.operate_id</code>.
     */
    public TRoleOperateRecord setOperateId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_role_operate.operate_id</code>.
     */
    @NotNull
    public Integer getOperateId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TRoleOperate.t_role_operate.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TRoleOperate.t_role_operate.role_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TRoleOperate.t_role_operate.operate_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getOperateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getOperateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoleOperateRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoleOperateRecord value2(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoleOperateRecord value3(Integer value) {
        setOperateId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoleOperateRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRoleOperateRecord
     */
    public TRoleOperateRecord() {
        super(TRoleOperate.t_role_operate);
    }

    /**
     * Create a detached, initialised TRoleOperateRecord
     */
    public TRoleOperateRecord(Integer id, Integer roleId, Integer operateId) {
        super(TRoleOperate.t_role_operate);

        set(0, id);
        set(1, roleId);
        set(2, operateId);
    }
}
