/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.records;


import com.example.mvc.table.tables.TRoomMemberCheck;

import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRoomMemberCheckRecord extends UpdatableRecordImpl<TRoomMemberCheckRecord> implements Record5<Integer, Integer, Integer, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1292667438;

    /**
     * Setter for <code>kelu.t_room_member_check.id</code>.
     */
    public TRoomMemberCheckRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_room_member_check.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kelu.t_room_member_check.room_id</code>.
     */
    public TRoomMemberCheckRecord setRoomId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_room_member_check.room_id</code>.
     */
    @NotNull
    public Integer getRoomId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kelu.t_room_member_check.user_id</code>.
     */
    public TRoomMemberCheckRecord setUserId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_room_member_check.user_id</code>.
     */
    @NotNull
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>kelu.t_room_member_check.postTime</code>.
     */
    public TRoomMemberCheckRecord setPostTime(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_room_member_check.postTime</code>.
     */
    public LocalDateTime getPostTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>kelu.t_room_member_check.account_id</code>.
     */
    public TRoomMemberCheckRecord setAccountId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_room_member_check.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, LocalDateTime, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, LocalDateTime, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TRoomMemberCheck.t_room_member_check.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TRoomMemberCheck.t_room_member_check.room_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TRoomMemberCheck.t_room_member_check.user_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return TRoomMemberCheck.t_room_member_check.postTime;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TRoomMemberCheck.t_room_member_check.account_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRoomId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getPostTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRoomId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getPostTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomMemberCheckRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomMemberCheckRecord value2(Integer value) {
        setRoomId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomMemberCheckRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomMemberCheckRecord value4(LocalDateTime value) {
        setPostTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomMemberCheckRecord value5(Integer value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomMemberCheckRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRoomMemberCheckRecord
     */
    public TRoomMemberCheckRecord() {
        super(TRoomMemberCheck.t_room_member_check);
    }

    /**
     * Create a detached, initialised TRoomMemberCheckRecord
     */
    public TRoomMemberCheckRecord(Integer id, Integer roomId, Integer userId, LocalDateTime postTime, Integer accountId) {
        super(TRoomMemberCheck.t_room_member_check);

        set(0, id);
        set(1, roomId);
        set(2, userId);
        set(3, postTime);
        set(4, accountId);
    }
}
