/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.records;


import com.example.mvc.table.tables.TTopicAttribute;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTopicAttributeRecord extends UpdatableRecordImpl<TTopicAttributeRecord> implements Record7<Integer, Integer, Byte, Byte, String, Byte, Byte> {

    private static final long serialVersionUID = -911457335;

    /**
     * Setter for <code>kelu.t_topic_attribute.id</code>.
     */
    public TTopicAttributeRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_topic_attribute.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kelu.t_topic_attribute.topic_id</code>. 话题id
     */
    public TTopicAttributeRecord setTopicId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_topic_attribute.topic_id</code>. 话题id
     */
    @NotNull
    public Integer getTopicId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kelu.t_topic_attribute.gender</code>. 0：男 1：女
     */
    public TTopicAttributeRecord setGender(Byte value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_topic_attribute.gender</code>. 0：男 1：女
     */
    @NotNull
    public Byte getGender() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>kelu.t_topic_attribute.age</code>. 年龄段 0：&lt;= 11岁 ; 1: 12~14岁; 2: 15~17岁; 3: 18~24岁; 4: 25~28岁; 5: 28岁以上
     */
    public TTopicAttributeRecord setAge(Byte value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_topic_attribute.age</code>. 年龄段 0：&lt;= 11岁 ; 1: 12~14岁; 2: 15~17岁; 3: 18~24岁; 4: 25~28岁; 5: 28岁以上
     */
    @NotNull
    public Byte getAge() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>kelu.t_topic_attribute.categoryIDs</code>. 学习标签 最大为3个
     */
    public TTopicAttributeRecord setCategoryIDs(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_topic_attribute.categoryIDs</code>. 学习标签 最大为3个
     */
    @NotNull
    @Size(max = 255)
    public String getCategoryIDs() {
        return (String) get(4);
    }

    /**
     * Setter for <code>kelu.t_topic_attribute.is_hot</code>. 是否热门 0 为 普通  1为热门
     */
    public TTopicAttributeRecord setIsHot(Byte value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_topic_attribute.is_hot</code>. 是否热门 0 为 普通  1为热门
     */
    @NotNull
    public Byte getIsHot() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>kelu.t_topic_attribute.is_old</code>.
     */
    public TTopicAttributeRecord setIsOld(Byte value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_topic_attribute.is_old</code>.
     */
    @NotNull
    public Byte getIsOld() {
        return (Byte) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Byte, Byte, String, Byte, Byte> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Byte, Byte, String, Byte, Byte> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TTopicAttribute.t_topic_attribute.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TTopicAttribute.t_topic_attribute.topic_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return TTopicAttribute.t_topic_attribute.gender;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return TTopicAttribute.t_topic_attribute.age;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TTopicAttribute.t_topic_attribute.categoryIDs;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return TTopicAttribute.t_topic_attribute.is_hot;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return TTopicAttribute.t_topic_attribute.is_old;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getTopicId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCategoryIDs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getIsHot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getIsOld();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTopicId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCategoryIDs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getIsHot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getIsOld();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTopicAttributeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTopicAttributeRecord value2(Integer value) {
        setTopicId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTopicAttributeRecord value3(Byte value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTopicAttributeRecord value4(Byte value) {
        setAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTopicAttributeRecord value5(String value) {
        setCategoryIDs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTopicAttributeRecord value6(Byte value) {
        setIsHot(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTopicAttributeRecord value7(Byte value) {
        setIsOld(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTopicAttributeRecord values(Integer value1, Integer value2, Byte value3, Byte value4, String value5, Byte value6, Byte value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TTopicAttributeRecord
     */
    public TTopicAttributeRecord() {
        super(TTopicAttribute.t_topic_attribute);
    }

    /**
     * Create a detached, initialised TTopicAttributeRecord
     */
    public TTopicAttributeRecord(Integer id, Integer topicId, Byte gender, Byte age, String categoryIDs, Byte isHot, Byte isOld) {
        super(TTopicAttribute.t_topic_attribute);

        set(0, id);
        set(1, topicId);
        set(2, gender);
        set(3, age);
        set(4, categoryIDs);
        set(5, isHot);
        set(6, isOld);
    }
}
