/*
 * This file is generated by jOOQ.
*/
package com.example.mvc.table.tables.records;


import com.example.mvc.table.tables.TUserMessage;

import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserMessageRecord extends UpdatableRecordImpl<TUserMessageRecord> implements Record4<Integer, Integer, String, LocalDateTime> {

    private static final long serialVersionUID = -1837501253;

    /**
     * Setter for <code>kelu.t_user_message.id</code>.
     */
    public TUserMessageRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_user_message.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kelu.t_user_message.userID</code>.
     */
    public TUserMessageRecord setUserID(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_user_message.userID</code>.
     */
    @NotNull
    public Integer getUserID() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kelu.t_user_message.content</code>.
     */
    public TUserMessageRecord setContent(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_user_message.content</code>.
     */
    @Size(max = 255)
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kelu.t_user_message.post_time</code>.
     */
    public TUserMessageRecord setPostTime(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kelu.t_user_message.post_time</code>.
     */
    public LocalDateTime getPostTime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TUserMessage.t_user_message.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TUserMessage.t_user_message.userID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TUserMessage.t_user_message.content;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return TUserMessage.t_user_message.post_time;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserID();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getPostTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserID();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getPostTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserMessageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserMessageRecord value2(Integer value) {
        setUserID(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserMessageRecord value3(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserMessageRecord value4(LocalDateTime value) {
        setPostTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserMessageRecord values(Integer value1, Integer value2, String value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TUserMessageRecord
     */
    public TUserMessageRecord() {
        super(TUserMessage.t_user_message);
    }

    /**
     * Create a detached, initialised TUserMessageRecord
     */
    public TUserMessageRecord(Integer id, Integer userID, String content, LocalDateTime postTime) {
        super(TUserMessage.t_user_message);

        set(0, id);
        set(1, userID);
        set(2, content);
        set(3, postTime);
    }
}
